import { text, type HallDefinition } from "../hall-kit.ts";

export const PRESENTATION_HALLS: HallDefinition[] = [
  {
    id: "showcase-screen-effects",
    number: 1,
    title: "Screen Effects",
    commands: [
      "screenFade",
      "screenTint",
      "screenFlash",
      "screenShake",
      "camera",
      "balloon",
      "screenBackdrop",
    ],
    palette: ["#14213d", "#274c77"],
    demo: [
      text("First, the whole screen fades out and in."),
      {
        op: "screenFade",
        direction: "out",
        duration: 0.25,
        color: { r: 8, g: 20, b: 48, a: 255 },
        wait: true,
      },
      {
        op: "screenFade",
        direction: "in",
        duration: 0.25,
        color: { r: 8, g: 20, b: 48, a: 255 },
        wait: true,
      },
      text("One named tint moves day to dusk to night."),
      {
        op: "screenTint",
        layer: "time-of-day",
        color: { r: 255, g: 232, b: 152, a: 40 },
        duration: 0.2,
        wait: true,
      },
      {
        op: "screenTint",
        layer: "time-of-day",
        color: { r: 238, g: 112, b: 64, a: 88 },
        duration: 0.2,
        wait: true,
      },
      {
        op: "screenTint",
        layer: "time-of-day",
        color: { r: 28, g: 54, b: 140, a: 112 },
        duration: 0.2,
        wait: true,
      },
      text("A zero-alpha target clears that named tint."),
      {
        op: "screenTint",
        layer: "time-of-day",
        color: { r: 28, g: 54, b: 140, a: 0 },
        duration: 0.2,
        wait: true,
      },
      {
        op: "screenFlash",
        color: { r: 255, g: 248, b: 220, a: 255 },
        intensity: 192,
        duration: 0.3,
        wait: true,
      },
      {
        op: "screenShake",
        strength: 6,
        speed: 5,
        duration: 0.4,
        wait: true,
      },
      text("The camera visits a tile, an actor, and me."),
      { op: "camera", target: { x: 16, y: 4 }, duration: 0.35, wait: true },
      { op: "camera", target: { event: "camera-target" }, duration: 0.35, wait: true },
      { op: "camera", target: "this", duration: 0.35, wait: true },
      { op: "camera", target: "player", duration: 0.35, wait: true },
      text("Balloons work on every character target."),
      {
        op: "balloon",
        target: "player",
        icon: "showcase-pulse",
        duration: 0.5,
        wait: true,
      },
      { op: "balloon", target: "this", icon: "showcase-ring" },
      text("This persistent balloon waits for a clear."),
      { op: "balloon", target: "this" },
      { op: "balloon", target: { event: "camera-target" }, icon: "showcase-pulse" },
      text("The observer can carry one independently."),
      { op: "balloon", target: { event: "camera-target" } },
      { op: "screenBackdrop", layer: "backdrop", variant: "gallery" },
      text("Backdrops persist beneath dialog."),
      { op: "screenBackdrop", layer: "backdrop", variant: "stars" },
      text("An exposed backdrop is replaced by the next selection."),
      { op: "screenBackdrop", layer: "backdrop", variant: null },
      text("All presentation effects are clear again."),
    ],
    events: [{
      id: "camera-target",
      name: "Camera and balloon target",
      x: 16,
      y: 7,
      pages: [{
        trigger: "action",
        sprite: "guide",
        blocks: true,
        commands: [text("I am a named camera and balloon target.")],
      }],
    }],
  },
  {
    id: "showcase-map-animations",
    number: 2,
    title: "Map Animations",
    commands: ["mapAnim", "stopAnim"],
    palette: ["#2b193d", "#6a4c93"],
    demo: [
      text("A waited one-shot plays above this tile."),
      {
        op: "mapAnim",
        id: "tile-once",
        anim: "showcase-pulse",
        x: 10,
        y: 5,
        layer: "above",
        loop: false,
        wait: true,
      },
      text("Loops can sit below actors or follow them."),
      {
        op: "mapAnim",
        id: "tile-loop",
        anim: "showcase-pulse",
        x: 9,
        y: 7,
        layer: "below",
        loop: true,
      },
      {
        op: "mapAnim",
        id: "player-aura",
        anim: "showcase-ring",
        target: "player",
        loop: true,
      },
      {
        op: "mapAnim",
        id: "moving-aura",
        anim: "showcase-ring",
        target: { event: "animation-target" },
        follow: true,
        loop: true,
      },
      {
        op: "mapAnim",
        id: "pinned-aura",
        anim: "showcase-pulse",
        target: { event: "animation-target" },
        follow: false,
        loop: true,
      },
      {
        op: "moveRoute",
        target: { event: "animation-target" },
        wait: true,
        route: {
          steps: ["moveUp", "wait", "moveDown"],
          repeat: false,
          skippable: false,
        },
      },
      text("The ring followed; the pulse stayed pinned."),
      { op: "stopAnim", id: "tile-loop" },
      text("Stopping by id removed only the floor loop."),
      { op: "stopAnim", anim: "showcase-ring" },
      text("Stopping by animation removed both rings."),
      { op: "stopAnim" },
      text("A bare stop removed every remaining effect."),
      { op: "switch", id: "presentation.anim.release", value: true },
      {
        op: "mapAnim",
        id: "waited-loop",
        anim: "showcase-ring",
        x: 10,
        y: 6,
        loop: true,
        wait: true,
      },
      text("A parallel stop released the waited loop."),
    ],
    events: [
      {
        id: "animation-target",
        name: "Moving animation target",
        x: 14,
        y: 7,
        pages: [{
          trigger: "action",
          sprite: "guide",
          blocks: true,
          commands: [text("My ring follows; my pulse stays behind.")],
        }],
      },
      {
        id: "animation-stop-timer",
        name: "Waited-loop release",
        x: 18,
        y: 13,
        pages: [
          { trigger: "action", commands: [] },
          {
            condition: { switch: "presentation.anim.release" },
            trigger: "parallel",
            commands: [
              { op: "wait", seconds: 0.75 },
              { op: "stopAnim", id: "waited-loop" },
              { op: "switch", id: "presentation.anim.release", value: false },
              { op: "exit" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "showcase-runtime-visuals",
    number: 3,
    title: "Runtime Appearance and Layers",
    commands: ["appearance", "layer", "tileProperty"],
    palette: ["#163832", "#2a9d8f"],
    demo: [
      text("Appearance targets the player, me, or an event."),
      { op: "appearance", target: "player", sprite: "guide", saveDefault: true },
      { op: "appearance", target: "player", sprite: "curator", opacity: 144, visible: true },
      {
        op: "if",
        if: { kind: "appearance", target: "player", sprite: "curator" },
        then: [text("The player appearance condition matched.")],
      },
      { op: "appearance", target: "this", sprite: "guide", opacity: 176, visible: true },
      {
        op: "appearance",
        target: { event: "appearance-target" },
        sprite: "portal",
        opacity: 112,
        visible: true,
      },
      {
        op: "if",
        if: { kind: "appearance", target: { event: "appearance-target" }, sprite: "portal" },
        then: [text("The named event condition matched too.")],
      },
      { op: "appearance", target: { event: "appearance-target" }, visible: false },
      { op: "wait", seconds: 0.25 },
      { op: "appearance", target: { event: "appearance-target" }, visible: true, opacity: null },
      {
        op: "appearance",
        target: { event: "appearance-target" },
        sprite: null,
        opacity: null,
        visible: null,
      },
      { op: "appearance", target: "this", sprite: null, opacity: null, visible: null },
      { op: "appearance", target: "player", sprite: null, opacity: null, visible: null },
      { op: "appearance", target: "player", sprite: null, saveDefault: true },
      text("Null restored every authored appearance."),
      { op: "layer", layer: "weather", variant: "day", visible: true },
      text("The screen layer starts with its day variant."),
      { op: "layer", layer: "weather", variant: "dusk" },
      text("The same layer can switch to dusk..."),
      { op: "layer", layer: "weather", variant: "night" },
      text("...and night, with no map transfer."),
      { op: "layer", layer: "weather", visible: false },
      text("Visibility is independent of the variant."),
      { op: "layer", layer: "weather", visible: null, variant: null },
      { op: "layer", layer: "gate", variant: "closed", visible: true },
      text("Map layers use the same command shape."),
      { op: "layer", layer: "gate", visible: false },
      { op: "layer", layer: "gate", visible: null, variant: null },
      {
        op: "tileProperty",
        x: 12,
        y: 7,
        passage: "block",
        enter: ["left"],
        exit: ["right"],
      },
      {
        op: "if",
        if: {
          kind: "tileProperty",
          x: 12,
          y: 7,
          passage: "block",
          enter: ["left"],
          exit: ["right"],
        },
        then: [text("The tile override condition matched.")],
      },
      { op: "tileProperty", x: 12, y: 7, passage: "pass", enter: [], exit: [] },
      text("Empty edge lists explicitly open the tile."),
      { op: "tileProperty", x: 12, y: 7, passage: null, enter: null, exit: null },
      text("Null restored the authored tile properties."),
    ],
    events: [{
      id: "appearance-target",
      name: "Appearance target",
      x: 14,
      y: 7,
      pages: [{
        trigger: "action",
        sprite: "guide",
        blocks: true,
        commands: [text("The curator can restyle me at runtime.")],
      }],
    }],
  },
];
