// AUTO-GENERATED by tests/fixtures/ka1-anim/gen-assets.ts — GameView asset
// literals (full strings so tools/build.ts bakes them) and per-map world
// geometry. Every map owns row-major 512px chunk image lists.

import type { GameAssets } from "../../../src/ui/game-assets.ts";

export const MAP_CANVAS_PX = 512;

export const MAP_GROUND: Record<string, readonly string[]> = {
  "ka1-field": ["assets/map-ka1-field-ground-0.png","assets/map-ka1-field-ground-1.png"],
  "ks1-persist-target": ["assets/map-ks1-persist-target-ground-0.png","assets/map-ks1-persist-target-ground-1.png"],
};

export const MAP_UPPER: Record<string, readonly string[]> = {
  "ka1-field": ["assets/map-ka1-field-upper-0.png","assets/map-ka1-field-upper-1.png"],
  "ks1-persist-target": ["assets/map-ks1-persist-target-upper-0.png","assets/map-ks1-persist-target-upper-1.png"],
};

export const MAP_CHUNK_COLUMNS: Record<string, number> = {
  "ka1-field": 2,
  "ks1-persist-target": 2,
};

export const MAP_MAX_CHUNKS = 2;

export const MAP_WORLD: Record<string, { w: number; h: number }> = {
  "ka1-field": { w: 640, h: 400 },
  "ks1-persist-target": { w: 640, h: 400 },
};

export const MAP_ORDER: readonly string[] = ["ka1-field","ks1-persist-target"];

export const NPC_SRC: Record<string, string> = {

};

// Player walker frames, facing order 0 down, 1 left, 2 up, 3 right.
export const PLAYER_IDLE: readonly [string, string, string, string] = [
  "assets/walker-idle-0.png",
  "assets/walker-idle-1.png",
  "assets/walker-idle-2.png",
  "assets/walker-idle-3.png",
];

export const PLAYER_WALK_L: readonly [string, string, string, string] = [
  "assets/walker-walkL-0.png",
  "assets/walker-walkL-1.png",
  "assets/walker-walkL-2.png",
  "assets/walker-walkL-3.png",
];

export const PLAYER_WALK_R: readonly [string, string, string, string] = [
  "assets/walker-walkR-0.png",
  "assets/walker-walkR-1.png",
  "assets/walker-walkR-2.png",
  "assets/walker-walkR-3.png",
];

export const ANIM_FRAMES: Record<string, { frames: readonly string[]; w: number; h: number }> = {
  "pulse": { frames: ["assets/anim-pulse-0.png","assets/anim-pulse-1.png","assets/anim-pulse-2.png","assets/anim-pulse-3.png"], w: 16, h: 16 },
  "ring": { frames: ["assets/anim-ring-0.png","assets/anim-ring-1.png"], w: 16, h: 16 },
  "tower": { frames: ["assets/anim-tower-0.png","assets/anim-tower-1.png"], w: 32, h: 64 },
};

export const GAME_ASSETS: GameAssets = {
  ground: MAP_GROUND,
  upper: MAP_UPPER,
  chunkColumns: MAP_CHUNK_COLUMNS,
  maxChunks: MAP_MAX_CHUNKS,
  maxActors: 1,
  world: MAP_WORLD,
  order: MAP_ORDER,
  npcSrc: NPC_SRC,
  player: { idle: PLAYER_IDLE, walkL: PLAYER_WALK_L, walkR: PLAYER_WALK_R },
  anims: ANIM_FRAMES,
};
