// AUTO-GENERATED by tests/fixtures/world-preview/gen-assets.ts — do not edit.
import type { GameAssets } from "../../../src/ui/game-assets.ts";

export const GAME_ASSETS: GameAssets = {
  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0, maxActors: 16,
  world: {
    "west": { w: 320, h: 192 },
    "east": { w: 320, h: 192 },
    "south": { w: 320, h: 192 },
    "north": { w: 320, h: 192 },
  },
  order: ["west","east","south","north"],
  npcSrc: {
    wander: "assets/npc/wander.png",
    gated: "assets/npc/gated.png",
    removed: "assets/npc/removed.png",
    rejected: "assets/npc/rejected.png",
    facing: "assets/npc/facing.png",
    under: "assets/npc/under.png",
    row: "assets/npc/row.png",
    tall: { idle: ["assets/npc/tall.png", "assets/npc/tall.png", "assets/npc/tall.png", "assets/npc/tall.png"], walkL: ["assets/npc/tall.png", "assets/npc/tall.png", "assets/npc/tall.png", "assets/npc/tall.png"], walkR: ["assets/npc/tall.png", "assets/npc/tall.png", "assets/npc/tall.png", "assets/npc/tall.png"], h: 32 },
    nrow: "assets/npc/nrow.png",
    wtall: { idle: ["assets/npc/wtall.png", "assets/npc/wtall.png", "assets/npc/wtall.png", "assets/npc/wtall.png"], walkL: ["assets/npc/wtall.png", "assets/npc/wtall.png", "assets/npc/wtall.png", "assets/npc/wtall.png"], walkR: ["assets/npc/wtall.png", "assets/npc/wtall.png", "assets/npc/wtall.png", "assets/npc/wtall.png"], h: 32 },
    atall: { idle: ["assets/npc/atall.png", "assets/npc/atall.png", "assets/npc/atall.png", "assets/npc/atall.png"], walkL: ["assets/npc/atall.png", "assets/npc/atall.png", "assets/npc/atall.png", "assets/npc/atall.png"], walkR: ["assets/npc/atall.png", "assets/npc/atall.png", "assets/npc/atall.png", "assets/npc/atall.png"], h: 32 },
    zshort: "assets/npc/zshort.png",
    ghost: "assets/npc/ghost.png",
    facer: { idle: ["assets/npc/facer-down.png", "assets/npc/facer-left.png", "assets/npc/facer-up.png", "assets/npc/facer-right.png"], walkL: ["assets/npc/facer-down.png", "assets/npc/facer-left.png", "assets/npc/facer-up.png", "assets/npc/facer-right.png"], walkR: ["assets/npc/facer-down.png", "assets/npc/facer-left.png", "assets/npc/facer-up.png", "assets/npc/facer-right.png"], h: 16 },
  },
  player: { idle: ["assets/player.png", "assets/player.png", "assets/player.png", "assets/player.png"], walkL: ["assets/player.png", "assets/player.png", "assets/player.png", "assets/player.png"], walkR: ["assets/player.png", "assets/player.png", "assets/player.png", "assets/player.png"] },
  stream: {
  chunkPx: 256,
  margin: 16,
  ground: {
    "west": ["ui:tile.preview-west-ground#0","ui:tile.preview-west-ground#1"],
    "east": ["ui:tile.preview-east-ground#0","ui:tile.preview-east-ground#1"],
    "south": ["ui:tile.preview-south-ground#0","ui:tile.preview-south-ground#1"],
    "north": ["ui:tile.preview-north-ground#0","ui:tile.preview-north-ground#1"],
  },
  upper: {
    "west": [null,null],
    "east": ["ui:tile.preview-east-upper#0",null],
    "south": [null,null],
    "north": [null,null],
  },
  columns: {
    "west": 2,
    "east": 2,
    "south": 2,
    "north": 2,
  },
},
};
