// Deterministically cook the three preview maps into streamed TILESET
// entries plus one solid-colour image per previewable character. The
// `facer` walker paints a different colour per facing so pixel probes can
// read the direction a preview or an active character shows.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { encodePNG } from "../../../vendor/pocketjs/tests/png.ts";
import {
  encodeStreamedLayer,
  pakManifest,
  streamEntryFile,
  streamManifestSource,
  type StreamEntry,
  type StreamedLayer,
} from "../../../tools/lib/stream.ts";
import {
  COLOURS,
  FACER_COLOURS,
  MAP_H,
  MAP_W,
  PLACED,
  PLAYER_COLOUR,
  TALL_SPRITES,
  UPPER_MARKERS,
  type Rgba,
} from "./fixture-data.ts";

const HERE = import.meta.dir;
const TILE = 16;
const CHUNK = 256;

function paintChunk(map: typeof PLACED[number], chunkX: number, chunkY: number, upper: boolean): Uint8Array {
  const rgba = new Uint8Array(CHUNK * CHUNK * 4);
  const markers = UPPER_MARKERS[map.id]!;
  for (let y = 0; y < CHUNK; y++) {
    const mapY = chunkY * CHUNK + y;
    if (mapY >= MAP_H * TILE) break;
    for (let x = 0; x < CHUNK; x++) {
      const mapX = chunkX * CHUNK + x;
      if (mapX >= MAP_W * TILE) break;
      const tileX = Math.floor(mapX / TILE);
      const tileY = Math.floor(mapY / TILE);
      const colour = !upper
        ? map.ground
        : markers.some(([mx, my]) => mx === tileX && my === tileY) ? map.upper : undefined;
      if (colour) rgba.set(colour, (y * CHUNK + x) * 4);
    }
  }
  return rgba;
}

const entries: StreamEntry[] = [];
const cooked = new Map<string, { ground: StreamedLayer; upper: StreamedLayer }>();
const columns = Math.ceil(MAP_W * TILE / CHUNK);
const rows = Math.ceil(MAP_H * TILE / CHUNK);
for (const map of PLACED) {
  const groundChunks: Uint8Array[] = [];
  const upperChunks: Uint8Array[] = [];
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < columns; x++) {
      groundChunks.push(paintChunk(map, x, y, false));
      upperChunks.push(paintChunk(map, x, y, true));
    }
  }
  const ground = encodeStreamedLayer(`preview-${map.id}-ground`, groundChunks, columns, rows, { chunkPx: CHUNK });
  const upper = encodeStreamedLayer(`preview-${map.id}-upper`, upperChunks, columns, rows, { chunkPx: CHUNK });
  entries.push(...ground.entries, ...upper.entries);
  cooked.set(map.id, { ground: ground.layer, upper: upper.layer });
}
for (const entry of entries) {
  const path = join(HERE, streamEntryFile(entry.key));
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, entry.blob);
}
writeFileSync(join(HERE, "pak.json"), JSON.stringify(pakManifest(entries), null, 2) + "\n");

function solid(colour: Rgba, height = TILE): Uint8Array {
  const rgba = new Uint8Array(TILE * height * 4);
  for (let i = 0; i < TILE * height; i++) rgba.set(colour, i * 4);
  return rgba;
}

const images: Record<string, { psm: number }> = {};
const write = (path: string, colour: Rgba, height = TILE): void => {
  mkdirSync(dirname(join(HERE, path)), { recursive: true });
  writeFileSync(join(HERE, path), encodePNG(solid(colour, height), TILE, height));
  images[path] = { psm: 3 };
};
write("assets/player.png", PLAYER_COLOUR);
const isTall = (name: string): boolean => (TALL_SPRITES as readonly string[]).includes(name);
for (const [name, colour] of Object.entries(COLOURS)) {
  write(`assets/npc/${name}.png`, colour, isTall(name) ? 32 : TILE);
}
const FACINGS = ["down", "left", "up", "right"] as const;
FACINGS.forEach((facing, index) => write(`assets/npc/facer-${facing}.png`, FACER_COLOURS[index]!));
writeFileSync(join(HERE, "images.json"), JSON.stringify(images, null, 2) + "\n");
writeFileSync(join(HERE, "sprites.json"), "{}\n");

const stream = streamManifestSource(PLACED.map((map) => ({
  id: map.id,
  width: MAP_W,
  height: MAP_H,
  ground: cooked.get(map.id)!.ground,
  upper: cooked.get(map.id)!.upper,
})), { chunkPx: CHUNK, margin: TILE });
const q = JSON.stringify;
const four = (src: string): string => `[${Array.from({ length: 4 }, () => q(src)).join(", ")}]`;
const facer = `[${FACINGS.map((facing) => q(`assets/npc/facer-${facing}.png`)).join(", ")}]`;
const npcSrc: string[] = Object.keys(COLOURS).map((name) => {
  const src = `assets/npc/${name}.png`;
  return isTall(name)
    ? `    ${name}: { idle: ${four(src)}, walkL: ${four(src)}, walkR: ${four(src)}, h: 32 },`
    : `    ${name}: ${q(src)},`;
});
npcSrc.push(`    facer: { idle: ${facer}, walkL: ${facer}, walkR: ${facer}, h: 16 },`);
writeFileSync(
  join(HERE, "assets-game.ts"),
  `// AUTO-GENERATED by tests/fixtures/world-preview/gen-assets.ts — do not edit.\n` +
    `import type { GameAssets } from "../../../src/ui/game-assets.ts";\n\n` +
    `export const GAME_ASSETS: GameAssets = {\n` +
    `  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0, maxActors: 16,\n` +
    `  world: {\n` +
    PLACED.map((map) => `    ${q(map.id)}: { w: ${MAP_W * TILE}, h: ${MAP_H * TILE} },`).join("\n") + `\n` +
    `  },\n` +
    `  order: ${q(PLACED.map((map) => map.id))},\n` +
    `  npcSrc: {\n${npcSrc.join("\n")}\n  },\n` +
    `  player: { idle: ${four("assets/player.png")}, walkL: ${four("assets/player.png")}, walkR: ${four("assets/player.png")} },\n` +
    `  stream: ${stream},\n` +
    `};\n`,
);
console.log(`world-preview fixture: ${PLACED.length} maps, ${entries.length} TILESET entries`);
