// src/engine/attract.ts — D1 attract mode + D2 takeover/rewind
// controller, folded over the same pure session reducer as live play
// (engine/session.ts).
//
// One principle governs the whole file: the reducer sees exactly ONE input
// stream, one u16 button mask per world frame. Demo and player frames are
// indistinguishable reducer inputs; the only difference is who chose the
// mask (the built-in tape or the live buttons). Display-only pacing ticks
// share the rewind timeline, but never call the reducer. That is why a
// paced demo visits the same world after every tape mask, takeover does not
// change the world, and rewind can restore both the world and the display.
//
//   idle N s with no input (boot or in play) -> attract starts from a
//            CLEAN reset, then loops the tape
//   attract: tape masks; after the final frame the world rests on the
//            victory state for holdFrames, then a clean reset to frame 0
//   any non-transport button during attract   -> takeover: that frame
//            still folds the tape mask (the world cannot jump), and from
//            the NEXT frame the live buttons drive; a "YOU HAVE CONTROL"
//            notice shows for two seconds
//   L (LTRIGGER)                             -> rewind 3 virtual seconds:
//            restore a retained keyframe and re-fold only the suffix
//   SELECT in play                           -> while the current frame is
//            still inside the tape prefix (or was rewound into it), the
//            demo resumes from exactly this frame; otherwise it restarts
//
// Rewind path: restore the nearest retained keyframe at or before the target,
// then run the ordinary reducer over only the suffix. Keyframes contain the
// complete JSON-shaped SessionState plus the controller's source/display
// cursors. A no-keyframe replay remains the reference path used by tests.
//
// Under SessionOptions.immutableState a published state is never written
// again, so a keyframe keeps the state itself instead of a deep copy: taking
// one allocates almost nothing and consecutive keyframes share every
// unchanged subtree. Without that contract keyframes stay deep copies.
// Either way the budget charges each keyframe its full serialized size, an
// upper bound on what a shared keyframe actually retains.

import type { MapRepository, ProjectSource, WorldTraversalMode } from "./types.ts";
import type { MapContentVersion } from "./map-repository.ts";
import type { WorldHandoffResolver } from "./world-handoff-contract.ts";
import { textModalPage, type Modal, type TextPaginator, type TextTokenResolver } from "./interpreter.ts";
import type { ExtensionOptions } from "./extensions.ts";
import type { BattleRules } from "./battle.ts";
import type { SceneRules } from "./scene.ts";
import { deepClone } from "./clone.ts";
import {
  acquireSessionMap,
  createSession,
  releaseSessionMapsExcept,
  startSession,
  stepSession,
  type SessionInput,
  type SessionOptions,
  type SceneOptions,
  type SessionEffectSink,
  type Session,
  type SessionState,
  type SessionTickDirection,
} from "./session.ts";

// Button masks (contracts/spec/spec.ts BTN), duplicated as constants to
// keep this engine module free of framework imports.
const BTN_SELECT = 0x0001;
const BTN_UP = 0x0010;
const BTN_RIGHT = 0x0020;
const BTN_DOWN = 0x0040;
const BTN_LEFT = 0x0080;
const BTN_LTRIGGER = 0x0100;
const BTN_RTRIGGER = 0x0200;
const BTN_ZL = 0x0400;
const BTN_ZR = 0x0800;
const BTN_TRIANGLE = 0x1000;
/** The d-pad portion of a mask; a tick-direction resolver replaces only
 *  these bits between the timeline folds of one low-rate host frame. */
const BTN_DIR_MASK = BTN_UP | BTN_DOWN | BTN_LEFT | BTN_RIGHT;
const BTN_CIRCLE = 0x2000;
const BTN_CROSS = 0x4000;
const BTN_SQUARE = 0x8000;
const BTN_START = 0x0008;

/** The published tapes are generated by the deterministic 60 Hz journey
 *  drivers. A slower host consumes several of these source frames per host
 *  frame, keeping tape time and the complete reducer state rate-independent. */
export const ATTRACT_TAPE_HZ = 60;

/** A complete dialog remains readable for this many virtual seconds. Longer
 *  text earns up to one extra second before the tape may advance it. */
export const ATTRACT_READ_HOLD_MIN_SECONDS = 1.5;
export const ATTRACT_READ_HOLD_MAX_SECONDS = 2.5;
export const ATTRACT_READ_HOLD_CHARS_PER_SECOND = 120;

/** Ten minutes of 60 Hz input, exactly one u16 per folded source frame. */
export const ATTRACT_INPUT_LOG_FRAMES = ATTRACT_TAPE_HZ * 60 * 10;

/** One minute of the canonical 60 Hz source timeline. Display-only pacing
 * ticks do not advance this counter, so captures land on the same reducer
 * frame at every host rate. */
export const ATTRACT_KEYFRAME_INTERVAL_FRAMES = ATTRACT_TAPE_HZ * 60;

/** Default cap for the deterministic serialized-payload estimate retained by
 * rewind keyframes. Oldest keyframes are evicted first. A large game's state
 * serializes to tens of KiB, so this keeps a few minutes of keyframes while
 * the retained heap stays a small fraction of the game's own. */
export const ATTRACT_KEYFRAME_MAX_BYTES = 2 * 1024 * 1024;

/** Default cap on the number of retained rewind keyframes. */
export const ATTRACT_KEYFRAME_MAX_COUNT = 64;

const ALL_BUTTONS =
  BTN_SELECT | BTN_START | BTN_UP | BTN_RIGHT | BTN_DOWN | BTN_LEFT |
  BTN_LTRIGGER | BTN_RTRIGGER | BTN_ZL | BTN_ZR |
  BTN_TRIANGLE | BTN_CIRCLE | BTN_CROSS | BTN_SQUARE;

/** L and SELECT are transport controls. Every other defined button, including
 *  R/ZL/ZR, hands the current tape frame to the player. */
const TAKEOVER_KEYS = ALL_BUTTONS & ~(BTN_LTRIGGER | BTN_SELECT);

// Low five bits retain the reviewer-visible timeline flags; high three bits
// encode idle/typing/arming/reading/done as 0..4 for exact rewind restore.
const T_SOURCE = 1;
const T_HOLD = 2;
const T_END = 4;
const T_MODAL = 8;
const T_TYPE = 16;
const T_DISPLAY = T_HOLD | T_END | T_TYPE;
type PresentationStage = 0 | 1 | 2 | 3 | 4;

/** Demo presentation is one step below the authored 30 cps typewriter. */
export const ATTRACT_TYPEWRITER_CPS = 15;

export function attractReadHoldSeconds(chars: number): number {
  const weighted = ATTRACT_READ_HOLD_MIN_SECONDS + Math.max(0, chars) / ATTRACT_READ_HOLD_CHARS_PER_SECOND;
  return Math.min(ATTRACT_READ_HOLD_MAX_SECONDS, weighted);
}

export type AttractPhase = "attract" | "play";
export type AttractSpeed = 1 | 2 | 4;

export interface AttractOptions {
  immutableState?: boolean;
  /** Virtual frames per second; seconds-based timings derive from it. */
  hz: number;
  /** Source rate of the published tape. Defaults to 60 Hz. Tests that feed
   *  an adaptive tape generated at another rate set this explicitly. */
  tapeHz?: number;
  /** No-input frames before attract starts/restarts. Default 10 s. */
  idleFrames?: number;
  /** Source-timeline frames the victory state rests before a clean reset. */
  endHoldFrames?: number;
  /** Rewind distance in virtual seconds. Default 3. */
  rewindSeconds?: number;
  /** Reducer/source frames between periodic rewind keyframes. Defaults to
   *  3,600 (one minute at 60 Hz). Zero disables periodic captures; map and
   *  battle boundaries are still captured when the byte budget is nonzero. */
  keyframeIntervalFrames?: number;
  /** Maximum estimated payload bytes retained by rewind keyframes. Defaults
   *  to 2 MiB. Zero disables all keyframes and keeps the from-zero fallback. */
  keyframeMaxBytes?: number;
  /** Maximum number of retained keyframes, oldest evicted first. Defaults to
   *  64. Zero disables all keyframes. */
  keyframeMaxCount?: number;
  /** Grown-world play (examples/grow): never auto-enter attract from
   *  idle (the world was the demo itself; there is no tape to play).
   *  SELECT then invokes onSelect instead of handing control to a tape. */
  attractEnabled?: boolean;
  onSelect?: () => void;
  /** Required when project is a ProjectShell. Repository cache residency is
   * derived and never enters the rewind timeline. */
  maps?: MapRepository;
  /** Exact reviewed predecessor builds accepted for save loading. */
  compatibleSaveContent?: readonly MapContentVersion[];
  /** The same pure game registrations accepted by createSession(). They live
   * outside the rewind timeline; refolds reuse them against fresh state. */
  extensions?: ExtensionOptions;
  battle?: BattleRules;
  /** KG1: game-scene reducers keyed by id, forwarded to createSession. */
  scenes?: Record<string, SceneRules>;
  scene?: SceneOptions;
  /** Message pagination, forwarded to createSession (pure, like the
   *  registrations above). */
  paginateText?: TextPaginator;
  /** Resolver for `{x:<key>}` text tokens, forwarded to createSession (the
   *  same one GameView registers for live play, so a demo, a rewind and a
   *  re-fold expand text identically). Called once per token when a box
   *  opens; must be a pure function of the view. Only consulted when the
   *  project declares `system.textTokens`. */
  textTokens?: TextTokenResolver;
  /** Replay identity. Missing on a non-empty tape means legacy-transfer. */
  worldTraversal?: WorldTraversalMode;
  /** Optional connected-world opening resolver forwarded to Session. */
  handoff?: WorldHandoffResolver;
  /** Pure game policy for movement capabilities on trusted openings. */
  handoffCapability?: SessionOptions["handoffCapability"];
}

/** Rewind history knobs a game may tune (DemoOptions.rewind forwards them). */
export type AttractRewindOptions = Pick<
  AttractOptions,
  "rewindSeconds" | "keyframeIntervalFrames" | "keyframeMaxBytes" | "keyframeMaxCount"
>;

export interface AttractStatus {
  phase: AttractPhase;
  /** Frames of tape played in the current attract loop (0..tape length). */
  demoFrame: number;
  /** Total frames of the tape. */
  tapeFrames: number;
  /** Frames left to show the "YOU HAVE CONTROL" notice (0 = hidden). */
  controlNotice: number;
  /** Frames left to flash "REWIND" (0 = hidden). */
  rewindNotice: number;
  /** Source-timeline frames left in the current complete-dialog reading hold. */
  readHold: number;
  /** Source-timeline frames already spent resting after the tape. */
  endHold: number;
  /** Frames of live inactivity (play only). */
  idle: number;
  /** True on the frame a clean loop/attract reset just happened. */
  loopReset: boolean;
  /** True on the frame L triggered a rewind (the UI resets its own
   *  press-edge history to the rewound held mask). */
  rewound: boolean;
}

export interface FoldResult {
  state: SessionState;
  status: AttractStatus;
}

export interface AttractKeyframeEntry {
  /** Position in the unified source/display timeline. */
  timelineFrame: number;
  /** Number of reducer inputs folded at this point. */
  sourceFrame: number;
  estimatedBytes: number;
  interval: boolean;
  mapBoundary: boolean;
  /** KG1: true when a scene (battle or game scene) opened or closed. */
  sceneBoundary: boolean;
}

export interface AttractKeyframeStats {
  count: number;
  estimatedBytes: number;
  maxBytes: number;
  maxCount: number;
  /** True when keyframes keep shared immutable states instead of copies. */
  shared: boolean;
  intervalFrames: number;
  evicted: number;
  /** Reducer inputs evaluated by the most recent rewind refold. */
  lastRefoldFrames: number;
  /** Unified timeline position from which that suffix refold started. */
  lastRefoldStart: number;
  entries: AttractKeyframeEntry[];
}

interface AttractKeyframe extends AttractKeyframeEntry {
  state: SessionState;
  worldAnimationTick: number;
  lastFolded: number;
  firstDivergence: number;
  demoFrame: number;
  endHold: number;
  readHold: number;
  displayTicks: number;
  pacingTicks: number;
  stage: PresentationStage;
}

/** Controller fields a failed step restores (see AttractController.step). */
interface AttractCheckpoint {
  state: SessionState;
  phase: AttractPhase;
  logBuf: Uint16Array;
  timelineBuf: Uint8Array;
  sceneSelectBuf: Int32Array | null;
  logLength: number;
  firstDivergence: number;
  demoFrame: number;
  endHold: number;
  readHold: number;
  displayTicks: number;
  stage: PresentationStage;
  carry: number;
  controlNotice: number;
  rewindNotice: number;
  idle: number;
  lastFolded: number;
  lastLive: number;
  sourceFrame: number;
  worldAnimationTickValue: number;
  pacingTicks: number;
  keyframes: AttractKeyframe[];
  keyframeBytes: number;
  keyframeEvictions: number;
  lastRefoldFrames: number;
  lastRefoldStart: number;
  loopReset: boolean;
  rewound: boolean;
  residentMaps: string[];
}

function optionInteger(name: string, value: number | undefined, fallback: number): number {
  const resolved = value ?? fallback;
  if (!Number.isSafeInteger(resolved) || resolved < 0) {
    throw new RangeError(`attract: ${name} must be a non-negative safe integer`);
  }
  return resolved;
}

const ASCII_ONLY = /^[\x00-\x7f]*$/;

/** UTF-8 length of JSON.stringify(value). QuickJS has no TextEncoder, and a
 * per-character loop over a large state's JSON costs milliseconds there, so
 * ASCII text (the usual case) is recognised by one native regex test and only
 * other text is counted unit by unit. */
function jsonUtf8Length(value: unknown): number {
  const text = JSON.stringify(value);
  if (ASCII_ONLY.test(text)) return text.length;
  let bytes = 0;
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    if (code < 0x80) bytes++;
    else if (code < 0x800) bytes += 2;
    else if (code >= 0xd800 && code <= 0xdbff && i + 1 < text.length) {
      const low = text.charCodeAt(i + 1);
      if (low >= 0xdc00 && low <= 0xdfff) {
        bytes += 4;
        i++;
      } else {
        bytes += 3;
      }
    } else bytes += 3;
  }
  return bytes;
}

export class AttractController {
  private readonly session: Session;
  private readonly project: ProjectSource;
  private readonly hz: number;
  private readonly timelineHz: number;
  private readonly idleFrames: number;
  private readonly endHoldFrames: number;
  private readonly rewindFrames: number;
  /** The configured rewind window in seconds (AttractOptions.rewindSeconds,
   *  default 3): the `demo.rewind` interface word fills its {seconds}
   *  placeholder with this. */
  readonly rewindSeconds: number;
  private readonly keyframeIntervalFrames: number;
  private readonly keyframeMaxBytes: number;
  private readonly keyframeMaxCount: number;
  /** Keyframes and the clean origin keep immutable states by reference. */
  private readonly sharedStates: boolean;
  private attractEnabled: boolean;
  private readonly onSelect?: () => void;
  private tape: readonly number[];
  private originState: SessionState | null = null;
  private originHeld = 0;
  private playbackSpeed: AttractSpeed = 1;

  state: SessionState;
  phase: AttractPhase = "play";
  /** The unified rewind timeline. Source/live entries carry reducer input;
   *  display-only entries carry zero and are skipped by refold(). The initial
   *  36,000-entry allocation is exactly 72,000 bytes (70.3125 KiB), matching
   *  the ten-minute 60 Hz payload described in PocketJS docs/DEVTOOLS.md. */
  private logBuf: Uint16Array;
  /** One compact controller byte per timeline entry. Its low bits distinguish
   *  reducer input from display ticks; its high bits retain presentation stage. */
  private timelineBuf: Uint8Array;
  /** Optional semantic scene selections from touch/click activation. This is
   *  allocated only after the first selection, so demo-enabled games that
   *  use controller input retain the historical memory footprint. -1 means
   *  that timeline entry carried no semantic selection. */
  private sceneSelectBuf: Int32Array | null = null;
  private logLength = 0;
  /** Smallest log index whose mask differs from the tape mask at that
   *  index (Infinity while every folded entry equals the tape). SELECT can
   *  resume the tape at the current position only while no earlier entry
   *  diverged — if all masks match, the state is by construction the tape
   *  replay state, regardless of who supplied the buttons. */
  private firstDivergence = Infinity;
  private demoFrame = 0;
  private endHold = 0;
  private readHold = 0;
  /** Display-clock ticks spent revealing the current text. These ticks never
   *  advance SessionState; presentedModal() applies them as a view overlay. */
  private displayTicks = 0;
  /** Display-hold ticks since the current modal started. This is retained
   * separately from readHold so a suffix scan can reconstruct the latter. */
  private pacingTicks = 0;
  private stage: PresentationStage = 0;
  /** Numerator for mapping one host frame onto the 60 Hz tape timeline. */
  private carry = 0;
  private controlNotice = 0;
  private rewindNotice = 0;
  private idle = 0;
  /** Mask folded on the previous step — reducer edges derive against it. */
  private lastFolded = 0;
  /** Previous LIVE mask — press-edge detection for transport/takeover. */
  private lastLive = 0;
  /** Number of reducer inputs in the retained timeline. Display-only entries
   * deliberately do not advance it. */
  private sourceFrame = 0;
  /** Reference ticks for which the map was visible at both ends. This is a
   * presentation clock: battle/display-only ticks do not advance it, and it
   * rewinds with the retained input timeline without entering SessionState. */
  private worldAnimationTickValue = 0;
  private keyframes: AttractKeyframe[] = [];
  private keyframeBytes = 0;
  private keyframeEvictions = 0;
  private lastRefoldFrames = 0;
  private lastRefoldStart = 0;
  private checkpoint: AttractCheckpoint | null = null;
  loopReset = false;
  rewound = false;

  constructor(project: ProjectSource, tape: readonly number[], opts: AttractOptions) {
    this.project = project;
    this.tape = tape;
    this.hz = opts.hz ?? 60;
    this.attractEnabled = opts.attractEnabled ?? true;
    this.timelineHz = this.attractEnabled ? (opts.tapeHz ?? ATTRACT_TAPE_HZ) : this.hz;
    this.session = createSession(project, this.timelineHz, {
      maps: opts.maps,
      compatibleSaveContent: opts.compatibleSaveContent,
      extensions: opts.extensions,
      battle: opts.battle,
      scenes: opts.scenes,
      scene: opts.scene,
      immutableState: opts.immutableState,
      paginateText: opts.paginateText,
      textTokens: opts.textTokens,
      worldTraversal: opts.worldTraversal ?? (tape.length > 0 ? "legacy-transfer" : project.worldTraversal),
      handoff: opts.handoff,
      handoffCapability: opts.handoffCapability,
    });
    this.idleFrames = opts.idleFrames ?? this.hz * 10;
    this.endHoldFrames = opts.endHoldFrames ?? this.timelineHz * 2;
    this.rewindSeconds = opts.rewindSeconds ?? 3;
    this.rewindFrames = Math.max(1, Math.round(this.rewindSeconds * this.timelineHz));
    this.keyframeIntervalFrames = optionInteger(
      "keyframeIntervalFrames",
      opts.keyframeIntervalFrames,
      ATTRACT_KEYFRAME_INTERVAL_FRAMES,
    );
    this.keyframeMaxBytes = optionInteger(
      "keyframeMaxBytes",
      opts.keyframeMaxBytes,
      ATTRACT_KEYFRAME_MAX_BYTES,
    );
    this.keyframeMaxCount = optionInteger(
      "keyframeMaxCount",
      opts.keyframeMaxCount,
      ATTRACT_KEYFRAME_MAX_COUNT,
    );
    this.sharedStates = opts.immutableState === true;
    const initialFrames = this.attractEnabled
      ? ATTRACT_INPUT_LOG_FRAMES
      : Math.max(1, this.timelineHz * 60 * 10);
    this.logBuf = new Uint16Array(initialFrames);
    this.timelineBuf = new Uint8Array(initialFrames);
    this.onSelect = opts.onSelect;
    this.state = startSession(project, this.session);
  }

  /** The session the UI reads map tables/worlds from. */
  getSession(): Session {
    return this.session;
  }

  /** Copy of the rewind timeline. Display-only ticks carry zero and are
   *  distinguished from reducer input by timelineBuf. */
  get inputLog(): number[] {
    return Array.from(this.logBuf.subarray(0, this.logLength));
  }

  /** Virtual 60 Hz timeline entries retained so far. */
  get length(): number {
    return this.logLength;
  }

  /** Allocated bytes for the u16 input payload, excluding controller metadata. */
  get inputLogAllocatedBytes(): number {
    return this.logBuf.byteLength;
  }

  /** Allocated bytes for input plus the controller timeline used to restore
   *  pacing and end-hold on rewind. */
  get historyAllocatedBytes(): number {
    return this.logBuf.byteLength + this.timelineBuf.byteLength +
      (this.sceneSelectBuf?.byteLength ?? 0);
  }

  /** Deterministic serialized-payload estimate for retained keyframes. This
   * is the quantity governed by keyframeMaxBytes; JS object overhead varies
   * by host and is intentionally not presented as portable byte accounting. */
  get keyframeEstimatedBytes(): number {
    return this.keyframeBytes;
  }

  /** Input/timeline typed-array allocation plus retained keyframe payload. */
  get rewindHistoryEstimatedBytes(): number {
    return this.historyAllocatedBytes + this.keyframeBytes;
  }

  /** Copy-only diagnostics for tests, profilers and an eventual devtools UI. */
  keyframeStats(): AttractKeyframeStats {
    return {
      count: this.keyframes.length,
      estimatedBytes: this.keyframeBytes,
      maxBytes: this.keyframeMaxBytes,
      maxCount: this.keyframeMaxCount,
      shared: this.sharedStates,
      intervalFrames: this.keyframeIntervalFrames,
      evicted: this.keyframeEvictions,
      lastRefoldFrames: this.lastRefoldFrames,
      lastRefoldStart: this.lastRefoldStart,
      entries: this.keyframes.map((keyframe) => ({
        timelineFrame: keyframe.timelineFrame,
        sourceFrame: keyframe.sourceFrame,
        estimatedBytes: keyframe.estimatedBytes,
        interval: keyframe.interval,
        mapBoundary: keyframe.mapBoundary,
        sceneBoundary: keyframe.sceneBoundary,
      })),
    };
  }

  /** Mask folded on the previous reducer step. Display-only ticks do not
   *  change it; after rewind it is the last retained world mask. */
  foldedMask(): number {
    return this.lastFolded;
  }

  /** Deterministic paint clock for native animated map sprites. */
  worldAnimationTick(): number {
    return this.worldAnimationTickValue;
  }

  status(): AttractStatus {
    return {
      phase: this.phase,
      demoFrame: this.demoFrame,
      tapeFrames: this.tape.length,
      controlNotice: this.controlNotice,
      rewindNotice: this.rewindNotice,
      readHold: this.readHold,
      endHold: this.endHold,
      idle: this.idle,
      loopReset: this.loopReset,
      rewound: this.rewound,
    };
  }

  /** Source steps folded per host frame while the tape owns input. Kept
   * separate from status() so adding demo controls does not change the
   * observable status shape of existing attract-mode games. */
  getPlaybackSpeed(): AttractSpeed {
    return this.playbackSpeed;
  }

  /** Change only presentation throughput. The reducer still receives the
   * same ordered u16 stream, so a tape's terminal state is speed-invariant. */
  setPlaybackSpeed(speed: AttractSpeed): void {
    if (speed !== 1 && speed !== 2 && speed !== 4) {
      throw new RangeError("attract: playback speed must be 1, 2, or 4");
    }
    this.playbackSpeed = speed;
  }

  /** Replace the clean origin used by chapter playback and rewind. Callers
   * must pass a state produced by the ordinary validated restore path. */
  loadState(
    restored: SessionState,
    held: number,
    tape: ArrayLike<number> & Iterable<number> = [],
    autoplay = false,
    speed: AttractSpeed = 1,
  ): SessionState {
    if (!Number.isInteger(held) || held < 0 || held > 0xffff) {
      throw new RangeError("attract: held input must be a u16 button mask");
    }
    for (let i = 0; i < tape.length; i++) {
      const mask = tape[i];
      if (!Number.isInteger(mask) || mask! < 0 || mask! > 0xffff) {
        throw new RangeError(`attract: tape[${i}] must be a u16 button mask`);
      }
    }
    this.setPlaybackSpeed(speed);
    acquireSessionMap(this.session, restored.mapId);
    releaseSessionMapsExcept(this.session, [restored.mapId]);
    const nextOrigin = deepClone(restored);
    this.originState = nextOrigin;
    this.originHeld = held >>> 0;
    this.tape = [...tape];
    this.attractEnabled = this.tape.length > 0;
    this.resetTimeline(
      autoplay && this.attractEnabled ? "attract" : "play",
      this.sharedStates ? nextOrigin : deepClone(nextOrigin),
      false,
    );
    return this.state;
  }

  /** Menu overlays consume raw buttons without folding a world frame. Keep
   * transport-edge history aligned so closing a menu cannot look like a
   * takeover or rewind press on the next frame. */
  syncLiveButtons(mask: number): void {
    this.lastLive = mask >>> 0;
  }

  private result(): FoldResult {
    return { state: this.state, status: this.status() };
  }

  /** Modal shown by the UI. During attract, the display clock reveals text at
   *  15 cps while the reducer advances only on source-mask ticks. */
  presentedModal(): Modal | null {
    const modal = this.state.interp.modal;
    if (this.phase !== "attract" || modal?.kind !== "text" || !this.modalPaced) return modal;
    // A message of several pages types the open one.
    const { start, end } = textModalPage(modal);
    const revealed = Math.min(
      end,
      start + Math.floor(this.displayTicks * ATTRACT_TYPEWRITER_CPS / this.timelineHz),
    );
    return { ...modal, revealed, complete: revealed >= end };
  }

  private get modalPaced(): boolean {
    return this.stage !== 0;
  }

  private resetDisplay(): void {
    this.readHold = 0;
    this.displayTicks = 0;
    this.pacingTicks = 0;
    this.stage = 0;
  }

  private cleanOrigin(): SessionState {
    if (!this.originState) return startSession(this.project, this.session);
    acquireSessionMap(this.session, this.originState.mapId);
    releaseSessionMapsExcept(this.session, [this.originState.mapId]);
    return this.sharedStates ? this.originState : deepClone(this.originState);
  }

  private resetTimeline(phase: AttractPhase, origin: SessionState, loopReset: boolean): void {
    this.loopReset = loopReset;
    this.phase = phase;
    this.idle = 0;
    this.controlNotice = 0;
    this.rewindNotice = 0;
    this.state = origin;
    this.logLength = 0;
    this.lastFolded = this.originHeld;
    this.lastLive = 0;
    this.demoFrame = 0;
    this.endHold = 0;
    this.resetDisplay();
    this.carry = 0;
    this.firstDivergence = Infinity;
    this.sourceFrame = 0;
    this.worldAnimationTickValue = 0;
    this.keyframes = [];
    this.keyframeBytes = 0;
    this.keyframeEvictions = 0;
    this.lastRefoldFrames = 0;
    this.lastRefoldStart = 0;
  }

  /** Fresh playthrough state and an empty unified input stream. The loop
   *  reset and attract entry both go through here, so no folded residue
   *  survives between plays. A loaded chapter becomes the clean origin. */
  startAttract(): void {
    this.resetTimeline("attract", this.cleanOrigin(), true);
  }

  /** Begin live play immediately from the current clean world (D3: the
   *  grown village IS the game, so there is no attract lead-in). */
  startPlay(): void {
    this.phase = "play";
    this.idle = 0;
    this.controlNotice = 0;
  }

  private append(mask: number, timelineFlags: number, sceneSelectIndex?: number): void {
    if (this.logLength >= this.logBuf.length) {
      const grown = new Uint16Array(this.logBuf.length * 2);
      grown.set(this.logBuf);
      this.logBuf = grown;
      const grownTimeline = new Uint8Array(this.timelineBuf.length * 2);
      grownTimeline.set(this.timelineBuf);
      this.timelineBuf = grownTimeline;
      if (this.sceneSelectBuf) {
        const grownSelect = new Int32Array(this.sceneSelectBuf.length * 2);
        grownSelect.fill(-1);
        grownSelect.set(this.sceneSelectBuf);
        this.sceneSelectBuf = grownSelect;
      }
    }
    const index = this.logLength;
    this.logBuf[index] = mask >>> 0;
    this.timelineBuf[index] = timelineFlags | (this.stage << 5);
    if (sceneSelectIndex !== undefined) {
      if (!this.sceneSelectBuf) {
        this.sceneSelectBuf = new Int32Array(this.logBuf.length);
        this.sceneSelectBuf.fill(-1);
      }
      this.sceneSelectBuf[index] = sceneSelectIndex;
    } else if (this.sceneSelectBuf) {
      // A rewind can make this slot reusable; erase its previous selection.
      this.sceneSelectBuf[index] = -1;
    }
    this.logLength++;
    if (timelineFlags & T_MODAL) this.pacingTicks = 0;
    else if (timelineFlags & T_HOLD) this.pacingTicks++;
  }

  private reduce(
    state: SessionState,
    mask: number,
    previous: number,
    effects?: SessionEffectSink,
    sceneSelectIndex?: number,
  ): SessionState {
    const pressed = mask & ~previous;
    const input: SessionInput = {
      buttons: mask,
      confirmEdge: !!(pressed & BTN_CIRCLE),
      cancelEdge: !!(pressed & BTN_CROSS),
      upEdge: !!(pressed & BTN_UP),
      downEdge: !!(pressed & BTN_DOWN),
      leftEdge: !!(pressed & BTN_LEFT),
      rightEdge: !!(pressed & BTN_RIGHT),
    };
    if (sceneSelectIndex !== undefined) input.selectIndex = sceneSelectIndex;
    return stepSession(this.session, state, input, effects);
  }

  private fold(
    mask: number,
    timelineFlags = 0,
    effects?: SessionEffectSink,
    sceneSelectIndex?: number,
  ): SessionState {
    const beforeMap = this.state.mapId;
    const beforeScene = this.state.scene !== null;
    const beforeModal = this.state.interp.modal;
    const beforeModalInstance = this.modalKey(this.state);
    this.state = this.reduce(this.state, mask, this.lastFolded, effects, sceneSelectIndex);
    if (!beforeScene && this.state.scene === null) {
      this.worldAnimationTickValue = (this.worldAnimationTickValue + 1) >>> 0;
    }
    this.lastFolded = mask >>> 0;
    const afterModal = this.state.interp.modal;
    const afterModalInstance = this.modalKey(this.state);
    const modalStarted = afterModal !== null && (
      beforeModal === null ||
      afterModalInstance !== beforeModalInstance ||
      (beforeModal.kind === "text" && afterModal.kind === "text" && beforeModal.complete && !afterModal.complete)
    );
    if (timelineFlags & T_SOURCE && modalStarted) {
      timelineFlags |= T_MODAL;
      this.displayTicks = 0;
      this.readHold = 0;
      this.stage = afterModal.kind === "text" ? 1 : 2;
    } else if (afterModal === null && (beforeModal !== null || this.modalPaced)) {
      this.resetDisplay();
    } else if (modalStarted) {
      // Player-owned dialogs use the reducer's authored typewriter.
      this.resetDisplay();
    }
    this.append(mask, timelineFlags, sceneSelectIndex);
    this.sourceFrame++;
    this.captureKeyframe(
      beforeMap !== this.state.mapId,
      beforeScene !== (this.state.scene !== null),
    );
    return this.state;
  }

  private captureKeyframe(mapBoundary: boolean, sceneBoundary: boolean): void {
    const interval = this.keyframeIntervalFrames > 0 &&
      this.sourceFrame % this.keyframeIntervalFrames === 0;
    if ((!interval && !mapBoundary && !sceneBoundary) || this.keyframeMaxBytes === 0 ||
      this.keyframeMaxCount === 0) return;

    const state = this.sharedStates ? this.state : deepClone(this.state);
    const payload = {
      state,
      worldAnimationTick: this.worldAnimationTickValue,
      timelineFrame: this.logLength,
      sourceFrame: this.sourceFrame,
      lastFolded: this.lastFolded,
      firstDivergence: this.firstDivergence,
      demoFrame: this.demoFrame,
      endHold: this.endHold,
      readHold: this.readHold,
      displayTicks: this.displayTicks,
      pacingTicks: this.pacingTicks,
      stage: this.stage,
      interval,
      mapBoundary,
      sceneBoundary,
    };
    const estimatedBytes = jsonUtf8Length(payload);
    if (estimatedBytes > this.keyframeMaxBytes) return;

    const keyframe: AttractKeyframe = { ...payload, estimatedBytes };
    let next = [...this.keyframes, keyframe];
    let bytes = this.keyframeBytes + estimatedBytes;
    let evicted = 0;
    while ((bytes > this.keyframeMaxBytes || next.length - evicted > this.keyframeMaxCount) &&
      evicted < next.length) {
      bytes -= next[evicted]!.estimatedBytes;
      evicted++;
    }
    if (evicted > 0) {
      next = next.slice(evicted);
      this.keyframeEvictions += evicted;
    }
    this.keyframes = next;
    this.keyframeBytes = bytes;
  }

  private keyframeAtOrBefore(target: number): AttractKeyframe | undefined {
    for (let i = this.keyframes.length - 1; i >= 0; i--) {
      const keyframe = this.keyframes[i]!;
      if (keyframe.timelineFrame <= target) return keyframe;
    }
    return undefined;
  }

  /** Re-fold the reducer entries in the first `target` timeline ticks from a
   *  fresh session. Display ticks are skipped: they presented the same world
   *  again and were never reducer input in the original run. */
  private refoldWithClock(
    target: number,
    masks: ArrayLike<number> = this.logBuf,
  ): { state: SessionState; worldAnimationTick: number } {
    const keyframe = masks === this.logBuf ? this.keyframeAtOrBefore(target) : undefined;
    let state: SessionState;
    let worldAnimationTick: number;
    let previous: number;
    let start: number;
    if (keyframe) {
      acquireSessionMap(this.session, keyframe.state.mapId);
      releaseSessionMapsExcept(this.session, [keyframe.state.mapId]);
      state = this.sharedStates ? keyframe.state : deepClone(keyframe.state);
      worldAnimationTick = keyframe.worldAnimationTick;
      previous = keyframe.lastFolded;
      start = keyframe.timelineFrame;
    } else {
      state = this.cleanOrigin();
      worldAnimationTick = 0;
      previous = this.originHeld;
      start = 0;
    }
    let folded = 0;
    for (let i = start; i < target; i++) {
      if (masks === this.logBuf) {
        const flags = this.timelineBuf[i]!;
        if (!(flags & T_SOURCE) && (flags & T_DISPLAY)) continue;
      }
      const mask = masks[i]!;
      const beforeScene = state.scene !== null;
      const retainedSelect = masks === this.logBuf ? this.sceneSelectBuf?.[i] : undefined;
      state = this.reduce(
        state,
        mask,
        previous,
        undefined,
        retainedSelect !== undefined && retainedSelect >= 0 ? retainedSelect : undefined,
      );
      if (!beforeScene && state.scene === null) {
        worldAnimationTick = (worldAnimationTick + 1) >>> 0;
      }
      previous = mask;
      folded++;
    }
    if (masks === this.logBuf) {
      this.lastRefoldStart = start;
      this.lastRefoldFrames = folded;
    }
    return { state, worldAnimationTick };
  }

  private refold(target: number, masks: ArrayLike<number> = this.logBuf): SessionState {
    return this.refoldWithClock(target, masks).state;
  }

  /** Plain replay is kept as a diagnostic seam used by acceptance probes. It
   *  is never used to replace the live paced world. */
  private replay(masks: ArrayLike<number>, count: number): SessionState {
    return this.refold(count, masks);
  }

  /** Restore controller-owned timeline state from the retained prefix. The
   *  world itself is rebuilt by refold(); these flags rebuild where the tape
   *  cursor and the two kinds of inserted idle time stood at that frame. */
  private restoreTimeline(target: number): void {
    const keyframe = this.keyframeAtOrBefore(target);
    const start = keyframe?.timelineFrame ?? 0;
    this.sourceFrame = keyframe?.sourceFrame ?? 0;
    this.demoFrame = keyframe?.demoFrame ?? 0;
    this.endHold = keyframe?.endHold ?? 0;
    this.displayTicks = keyframe?.displayTicks ?? 0;
    this.pacingTicks = keyframe?.pacingTicks ?? 0;
    this.stage = keyframe?.stage ?? 0;
    this.lastFolded = keyframe?.lastFolded ?? this.originHeld;
    this.firstDivergence = keyframe?.firstDivergence ?? Infinity;
    let exactReadHold = keyframe?.readHold ?? 0;
    for (let i = start; i < target; i++) {
      const flags = this.timelineBuf[i]!;
      if (flags & T_MODAL) {
        this.displayTicks = 0;
        this.pacingTicks = 0;
      } else {
        if (flags & T_TYPE) this.displayTicks++;
        if (flags & T_HOLD) this.pacingTicks++;
      }
      if (flags & T_SOURCE) {
        if (this.logBuf[i] !== this.tape[this.demoFrame] && this.firstDivergence === Infinity) {
          this.firstDivergence = i;
        }
        this.demoFrame++;
        this.endHold = 0;
      } else if (!(flags & T_DISPLAY) && this.firstDivergence === Infinity) {
        this.firstDivergence = i;
      }
      if ((flags & T_SOURCE) || !(flags & T_DISPLAY)) {
        this.lastFolded = this.logBuf[i]!;
        this.sourceFrame++;
      }
      if (flags & T_END) this.endHold++;
      this.stage = (flags >>> 5) as PresentationStage;
      exactReadHold = -1;
    }
    this.demoFrame = Math.min(this.demoFrame, this.tape.length);
    if (!this.modalPaced) this.displayTicks = 0;
    this.readHold = exactReadHold >= 0
      ? exactReadHold
      : this.stage === 3
        ? Math.max(0, this.holdFrames() - this.pacingTicks)
        : 0;
  }

  private truncateKeyframes(target: number): void {
    const firstRemoved = this.keyframes.findIndex((keyframe) => keyframe.timelineFrame > target);
    if (firstRemoved < 0) return;
    const removed = this.keyframes.slice(firstRemoved);
    this.keyframes = this.keyframes.slice(0, firstRemoved);
    for (const keyframe of removed) this.keyframeBytes -= keyframe.estimatedBytes;
  }

  /** Rewind `rewindFrames` (or to frame 0). */
  private rewind(): void {
    this.rewound = true;
    const target = Math.max(0, this.logLength - this.rewindFrames);
    const restored = this.refoldWithClock(target);
    this.state = restored.state;
    this.worldAnimationTickValue = restored.worldAnimationTick;
    this.rewindNotice = this.hz;
    this.controlNotice = 0;
    this.restoreTimeline(target);
    this.logLength = target;
    this.truncateKeyframes(target);
    this.carry = Math.ceil(target * this.hz / this.timelineHz) * this.timelineHz - target * this.hz;
    this.idle = 0;
  }

  /** One virtual frame. `liveButtons` is the raw held mask from the host;
   *  the controller decides whether the tape or the player owns it. A
   *  repository miss rolls the whole host frame back, including low-rate
   *  multi-fold bookkeeping, so a caller can prepare bytes and retry it. */
  step(
    liveButtons: number,
    effects?: SessionEffectSink,
    tickDirection?: SessionTickDirection,
    sceneSelectIndex?: number,
  ): FoldResult {
    if (sceneSelectIndex !== undefined &&
      (!Number.isInteger(sceneSelectIndex) || sceneSelectIndex < 0 || sceneSelectIndex > 0x7fffffff)) {
      throw new RangeError("attract: sceneSelectIndex must be a non-negative i32");
    }
    if (!this.session.repository?.prepare) {
      return this.stepUnchecked(liveButtons, effects, tickDirection, sceneSelectIndex);
    }
    // A repository miss rolls the whole controller back. The checkpoint is
    // one reused record, every field rewritten here, so a demo-enabled game
    // allocates nothing per frame for it.
    const cp = this.checkpoint ??= { residentMaps: [] as string[] } as AttractCheckpoint;
    cp.state = this.state;
    cp.phase = this.phase;
    cp.logBuf = this.logBuf;
    cp.timelineBuf = this.timelineBuf;
    cp.sceneSelectBuf = this.sceneSelectBuf;
    cp.logLength = this.logLength;
    cp.firstDivergence = this.firstDivergence;
    cp.demoFrame = this.demoFrame;
    cp.endHold = this.endHold;
    cp.readHold = this.readHold;
    cp.displayTicks = this.displayTicks;
    cp.stage = this.stage;
    cp.carry = this.carry;
    cp.controlNotice = this.controlNotice;
    cp.rewindNotice = this.rewindNotice;
    cp.idle = this.idle;
    cp.lastFolded = this.lastFolded;
    cp.lastLive = this.lastLive;
    cp.sourceFrame = this.sourceFrame;
    cp.worldAnimationTickValue = this.worldAnimationTickValue;
    cp.pacingTicks = this.pacingTicks;
    cp.keyframes = this.keyframes;
    cp.keyframeBytes = this.keyframeBytes;
    cp.keyframeEvictions = this.keyframeEvictions;
    cp.lastRefoldFrames = this.lastRefoldFrames;
    cp.lastRefoldStart = this.lastRefoldStart;
    cp.loopReset = this.loopReset;
    cp.rewound = this.rewound;
    cp.residentMaps.length = 0;
    for (const id of this.session.maps.keys()) cp.residentMaps.push(id);
    try {
      const result = this.stepUnchecked(liveButtons, effects, tickDirection, sceneSelectIndex);
      // The step succeeded, so the rollback snapshot is stale. Resync its
      // heavy references onto the live objects: a keyframe generation this
      // step evicted (or a published state it retired) must not stay alive
      // just because the checkpoint still names it, until the next step
      // rewrites these fields.
      cp.state = this.state;
      cp.keyframes = this.keyframes;
      cp.logBuf = this.logBuf;
      cp.timelineBuf = this.timelineBuf;
      cp.sceneSelectBuf = this.sceneSelectBuf;
      return result;
    } catch (error) {
      this.state = cp.state;
      this.phase = cp.phase;
      this.logBuf = cp.logBuf;
      this.timelineBuf = cp.timelineBuf;
      this.sceneSelectBuf = cp.sceneSelectBuf;
      this.logLength = cp.logLength;
      this.firstDivergence = cp.firstDivergence;
      this.demoFrame = cp.demoFrame;
      this.endHold = cp.endHold;
      this.readHold = cp.readHold;
      this.displayTicks = cp.displayTicks;
      this.stage = cp.stage;
      this.carry = cp.carry;
      this.controlNotice = cp.controlNotice;
      this.rewindNotice = cp.rewindNotice;
      this.idle = cp.idle;
      this.lastFolded = cp.lastFolded;
      this.lastLive = cp.lastLive;
      this.sourceFrame = cp.sourceFrame;
      this.worldAnimationTickValue = cp.worldAnimationTickValue;
      this.pacingTicks = cp.pacingTicks;
      this.keyframes = cp.keyframes;
      this.keyframeBytes = cp.keyframeBytes;
      this.keyframeEvictions = cp.keyframeEvictions;
      this.lastRefoldFrames = cp.lastRefoldFrames;
      this.lastRefoldStart = cp.lastRefoldStart;
      this.loopReset = cp.loopReset;
      this.rewound = cp.rewound;
      for (const id of cp.residentMaps) acquireSessionMap(this.session, id);
      releaseSessionMapsExcept(this.session, cp.residentMaps);
      throw error;
    }
  }


  private stepUnchecked(
    liveButtons: number,
    effects?: SessionEffectSink,
    tickDirection?: SessionTickDirection,
    sceneSelectIndex?: number,
  ): FoldResult {
    this.loopReset = false;
    this.rewound = false;
    const live = liveButtons >>> 0;
    const livePressed = live & ~this.lastLive;
    this.lastLive = live;
    if (this.controlNotice > 0) this.controlNotice--;
    if (this.rewindNotice > 0) this.rewindNotice--;

    // L rewinds in either phase: during attract it scrubs the demo back.
    // The transport press folds no world frame itself; the next frame
    // continues from the rewound position.
    if (livePressed & BTN_LTRIGGER) {
      this.rewind();
      return this.result();
    }

    if (this.phase === "play") {
      // SELECT hands control back to the demo. In grown-world play
      // (attractEnabled:false) there is no demo; the callback returns to
      // the growth/timeline screen instead.
      if (livePressed & BTN_SELECT) {
        if (!this.attractEnabled || this.tape.length === 0) {
          if (this.onSelect) this.onSelect();
          return this.result();
        }
        if (this.firstDivergence === Infinity) {
          this.phase = "attract";
          this.restoreTimeline(this.logLength);
          this.carry = 0;
          this.idle = 0;
        } else {
          this.startAttract();
        }
        return this.result();
      }

      if (live === 0) {
        this.idle++;
        if (this.attractEnabled && this.tape.length > 0 && this.idle >= this.idleFrames) {
          // The idle frame that crosses the threshold starts attract from
          // a CLEAN world; it folds nothing itself, so attract frame 0 is
          // the next step.
          this.startAttract();
          return this.result();
        }
      } else {
        this.idle = 0;
      }
      this.foldLive(live, effects, tickDirection, sceneSelectIndex);
      return this.result();
    }

    // ---- attract -------------------------------------------------------
    // SELECT during attract restarts the loop from frame 0.
    if (livePressed & BTN_SELECT) {
      this.startAttract();
      return this.result();
    }

    // Takeover: the pressed frame still folds the tape mask, so state at
    // frame k is byte-identical to a run that never took over (takeover
    // changes only the input SOURCE from k+1). A held takeover button
    // drives from the next frame; a one-frame tap is the ownership gesture
    // and is consumed as such.
    if (livePressed & TAKEOVER_KEYS) {
      this.foldAttract(effects);
      this.phase = "play";
      this.controlNotice = Math.min(this.hz * 2, 120);
      this.idle = 0;
      return this.result();
    }

    // The source tape is frozen at timelineHz (60 Hz for both shipped demos).
    // Fold as many source frames as this host frame covers. Because every
    // source frame is retained, the final SessionState — including clocks,
    // NPCs and RNG — is field-identical at 60/30/20/4 Hz.
    this.foldAttract(effects);
    return this.result();
  }

  private foldAttract(effects?: SessionEffectSink): void {
    this.carry += this.timelineHz * this.playbackSpeed;
    while (this.phase === "attract" && this.carry >= this.hz) {
      this.carry -= this.hz;
      const beforeDemo = this.demoFrame;
      const beforeModal = this.presentedModal();
      const beforeModalComplete = beforeModal?.kind === "text" && beforeModal.complete;
      const beforeReadHold = this.readHold;
      this.foldTapeOrHold(effects);
      const afterModal = this.presentedModal();
      const afterModalComplete = afterModal?.kind === "text" && afterModal.complete;
      // A host presents only the state after all source folds for that host
      // frame. Stop at display-worthy boundaries so even a 4 Hz host shows
      // the fully revealed text and the final tape frame for a whole frame.
      if (
        this.loopReset ||
        (beforeDemo < this.tape.length && this.demoFrame === this.tape.length) ||
        (!beforeModalComplete && afterModalComplete) ||
        (beforeModal?.kind !== "choices" && afterModal?.kind === "choices") ||
        (beforeReadHold > 0 && this.readHold === 0)
      ) {
        // Preserve every accumulated source-frame credit. Returning here
        // exposes the boundary for one host paint; the remainder is folded
        // on the next host call, avoiding low-rate duration drift.
        break;
      }
    }
  }

  private foldLive(
    mask: number,
    effects?: SessionEffectSink,
    tickDirection?: SessionTickDirection,
    sceneSelectIndex?: number,
  ): void {
    this.carry += this.timelineHz;
    while (this.carry >= this.hz) {
      this.carry -= this.hz;
      const selectIndex = sceneSelectIndex;
      sceneSelectIndex = undefined;
      if (
        selectIndex === undefined &&
        this.firstDivergence === Infinity &&
        this.demoFrame < this.tape.length &&
        mask === this.tape[this.demoFrame]
      ) {
        this.demoFrame++;
        this.fold(mask, T_SOURCE, effects);
      } else {
        if (this.firstDivergence === Infinity) this.firstDivergence = this.logLength;
        this.fold(mask, 0, effects, selectIndex);
      }
      // The resolver advances the view-local route at the timeline (reference)
      // tick boundary; its bit replaces the d-pad on the NEXT fold, so a turn
      // inside one low-rate host frame is taken at the tile. The last fold of
      // the batch leaves the route to the next frame's first resolver call.
      if (tickDirection && this.carry >= this.hz) {
        mask = (mask & ~BTN_DIR_MASK) | (tickDirection(this.state) | 0);
      }
    }
  }

  private holdFrames(): number {
    const modal = this.state.interp.modal;
    const seconds = modal?.kind === "text"
      ? attractReadHoldSeconds(textModalPageLength(modal))
      : modal?.kind === "choices" ? ATTRACT_READ_HOLD_MIN_SECONDS : 0;
    return seconds === 0 ? 0 : Math.max(1, Math.ceil(seconds * this.timelineHz));
  }

  private modalKey(state: SessionState): string | null {
    const modal = state.interp.modal;
    if (!modal) return null;
    const fiber = state.interp.main?.key === modal.fiber
      ? state.interp.main
      : state.interp.parallels[modal.fiber];
    if (!fiber) return modal.kind + modal.fiber;
    // The compiled instruction path identifies the modal command. It stays
    // fixed while that instance is open and changes when the same fiber
    // advances into another command, even if both commands have equal copy.
    return modal.kind + fiber.key + fiber.stack.map((frame) => frame.pc).join(",");
  }

  /** Advance one 60 Hz display tick for the current modal. The world remains
   *  unchanged: these entries exist only so rewind and low-rate scheduling
   *  can reproduce the exact presentation position. */
  private paceModalDisplay(effects?: SessionEffectSink): boolean {
    const modal = this.state.interp.modal;
    if (!modal || !this.modalPaced || this.stage === 4) return false;

    if (this.stage === 1) {
      if (modal.kind !== "text") {
        this.stage = 3;
        this.readHold = this.holdFrames();
      } else if (this.displayTicks < Math.max(1, Math.ceil(textModalPageLength(modal) * this.timelineHz / ATTRACT_TYPEWRITER_CPS))) {
        this.displayTicks++;
        const nextSource = this.tape[this.demoFrame] ?? 0;
        const heldContinues = this.lastFolded !== 0 && (nextSource & this.lastFolded) !== 0;
        const shouldAdvanceSource = !modal.complete &&
          this.demoFrame < this.tape.length &&
          (heldContinues || this.displayTicks % 2 === 0);
        // While text types, the source world runs at half speed. A display tick
        // after a release is retained for rewind; ticks while a button remains
        // held consume host time without creating a false release in the log.
        if (shouldAdvanceSource) {
          const mask = this.tape[this.demoFrame]!;
          this.demoFrame++;
          this.fold(mask, T_SOURCE | T_TYPE, effects);
        }
        if (!shouldAdvanceSource) this.append(0, T_TYPE);
        return true;
      } else {
        this.stage = 2;
      }
    }

    if (this.stage === 2) {
      if (this.lastFolded !== 0 && this.demoFrame < this.tape.length) {
        const mask = this.tape[this.demoFrame]!;
        this.demoFrame++;
        this.fold(mask, T_SOURCE, effects);
        return true;
      }
      this.stage = 3;
      this.readHold = this.holdFrames();
    }

    if (this.stage !== 3 || this.readHold <= 0) {
      this.stage = 4;
      this.readHold = 0;
      return false;
    }
    this.readHold--;
    this.append(0, T_HOLD);
    if (this.readHold === 0) this.stage = 4;
    return true;
  }

  /** Present a display tick or fold the next source mask. Terminal rest also
   *  freezes the completed world, then starts a clean loop. */
  private foldTapeOrHold(effects?: SessionEffectSink): void {
    if (this.demoFrame < this.tape.length) {
      if (this.paceModalDisplay(effects)) return;
      const mask = this.tape[this.demoFrame]!;
      this.demoFrame++;
      this.fold(mask, T_SOURCE, effects);
      return;
    }
    this.endHold++;
    this.append(0, T_END);
    if (this.endHold >= this.endHoldFrames) this.startAttract();
  }
}

/** Code points on a text box's open page (the whole text for one page). */
function textModalPageLength(modal: Extract<Modal, { kind: "text" }>): number {
  const { start, end } = textModalPage(modal);
  return end - start;
}
