// tests/fixtures/rpgmaker/gen-fixtures.ts — author the two RPG Maker
// fixture projects the importer is tested against.
//
//   bun tests/fixtures/rpgmaker/gen-fixtures.ts [outDir]
//
// Outputs (committed; every byte is regenerated by this script, default
// outDir is this directory):
//   hollow-mz/   MZ flavour, 16 px tiles: village, house/shop, cave, one
//                battle placeholder
//   stage-mv/    MV flavour, 48 px tiles: one stage map with an autorun
//                opening cutscene
//
// Each project is a `data/` directory in the public MV/MZ JSON layout and an
// `img/` directory of generated placeholder art (art.ts). Nothing is copied
// from any RPG Maker runtime package or game: names, maps, events and pixels
// are authored here. Audio files are referenced by name only and are not
// written. README.md has the walkthroughs the input tapes follow.
//
// Autotile ids are painted with any shape and then passed through
// reshapeAutotiles, so the stored shapes are the ones the editor would save.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { TILE_ID_A5, makeAutotileId, reshapeAutotiles } from "../../../tools/rpgmaker-import/autotile.ts";
import type {
  RmActor,
  RmAudio,
  RmCommand,
  RmCommonEvent,
  RmEvent,
  RmEventPage,
  RmItem,
  RmMap,
  RmMapInfo,
  RmMoveCommand,
  RmMoveRoute,
  RmPageConditions,
  RmPageImage,
  RmSystem,
  RmTileset,
  RmTroop,
} from "../../../tools/rpgmaker-import/rm-types.ts";
import {
  Canvas,
  TS,
  balloonSheet,
  characterSheet,
  chest,
  door,
  golem,
  hsl,
  hueMaterial,
  material,
  moth,
  person,
  plainTile,
  rgb,
  shade,
  sheetA1,
  sheetA2,
  sheetA3,
  sheetA4,
  sheetA5,
  sheetB,
  singleSheet,
  texel,
  type Material,
  type TileDraw,
} from "./art.ts";

export const FIXTURE_PROJECTS = ["hollow-mz", "stage-mv"] as const;

/** Relative path -> contents. */
type Files = Map<string, string | Uint8Array>;

// --- JSON in the editors' layout -------------------------------------------------
//
// The editors write object keys in alphabetical order, database files one
// record per line, and maps with `data` and `events` last (events one per
// line). Sorting keys here keeps every run byte-identical.

function sortKeys(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(sortKeys);
  if (v !== null && typeof v === "object") {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(v).sort()) out[k] = sortKeys((v as Record<string, unknown>)[k]);
    return out;
  }
  return v;
}

const j = (v: unknown): string => JSON.stringify(sortKeys(v));

const recordsJson = (records: readonly unknown[]): string => `[\n${records.map(j).join(",\n")}\n]`;

function mapJson(map: RmMap): string {
  const { data, events, ...header } = map;
  const head = j(header);
  return `${head.slice(0, -1)},\n"data":${j(data)},\n"events":${recordsJson(events)}\n}`;
}

// --- event commands ---------------------------------------------------------------

const cmd = (code: number, ...parameters: unknown[]): RmCommand => ({ code, indent: 0, parameters });

type Part = RmCommand | readonly RmCommand[];

const seq = (...parts: Part[]): RmCommand[] => parts.flatMap((p) => (Array.isArray(p) ? p : [p as RmCommand]));

/** A command list: the parts plus the closing end-of-list command. */
const list = (...parts: Part[]): RmCommand[] => [...seq(...parts), cmd(0)];

/** A nested body: one indent deeper, closed by its own end command. */
const nest = (...parts: Part[]): RmCommand[] => [
  ...seq(...parts).map((c) => ({ ...c, indent: c.indent + 1 })),
  { code: 0, indent: 1, parameters: [] },
];

/** Show Text. MZ adds the speaker name as the fifth parameter. */
const mzText = (speaker: string, ...lines: string[]): RmCommand[] => [
  cmd(101, "", 0, 0, 2, speaker),
  ...lines.map((l) => cmd(401, l)),
];
const mvText = (...lines: string[]): RmCommand[] => [cmd(101, "", 0, 0, 2), ...lines.map((l) => cmd(401, l))];
/** MV Show Text with a background (0 window, 1 dim, 2 transparent) and a
 *  position type (0 top, 1 middle, 2 bottom). */
const mvTextAt = (background: number, position: number, ...lines: string[]): RmCommand[] => [
  cmd(101, "", 0, background, position),
  ...lines.map((l) => cmd(401, l)),
];

/** Conditional Branch with an optional Else. */
const ifThen = (cond: unknown[], then: Part[], otherwise?: Part[]): RmCommand[] => [
  cmd(111, ...cond),
  ...nest(...then),
  ...(otherwise ? [cmd(411), ...nest(...otherwise)] : []),
  cmd(412),
];

// Conditional Branch operands.
const ifSwitch = (id: number, on = true): unknown[] => [0, id, on ? 0 : 1];
/** op: 0 ==, 1 >=, 2 <=, 3 >, 4 <, 5 != (constant operand). */
const ifVar = (id: number, op: number, value: number): unknown[] => [1, id, 0, value, op];
const ifItem = (id: number): unknown[] => [8, id];

/** Show Choices. cancelType -2 adds a When Cancel branch. */
function choices(
  labels: string[],
  cancelType: number,
  defaultType: number,
  branches: Part[][],
  cancel?: Part[],
): RmCommand[] {
  return [
    cmd(102, labels, cancelType, defaultType, 2, 0),
    ...labels.flatMap((label, i) => [cmd(402, i, label), ...nest(...branches[i]!)]),
    ...(cancel ? [cmd(403, 6, null), ...nest(...cancel)] : []),
    cmd(404),
  ];
}

const loop = (...body: Part[]): RmCommand[] => [cmd(112), ...nest(...body), cmd(413)];

/** Battle Processing with its result branches. */
function battle(troopId: number, win: Part[], escape: Part[], lose: Part[]): RmCommand[] {
  return [
    cmd(301, 0, troopId, true, true),
    cmd(601),
    ...nest(...win),
    cmd(602),
    ...nest(...escape),
    cmd(603),
    ...nest(...lose),
    cmd(604),
  ];
}

/** Shop Processing: [type, id, priceType, price] goods. */
const shop = (goods: number[][], purchaseOnly: boolean): RmCommand[] => [
  cmd(302, ...goods[0]!, purchaseOnly),
  ...goods.slice(1).map((g) => cmd(605, ...g)),
];

/** Control Variables. op 0 set, 1 add; operand 0 constant, 1 variable,
 *  2 random (min, max). */
const setVar = (id: number, value: number): RmCommand => cmd(122, id, id, 0, 0, value);
const addVar = (id: number, value: number): RmCommand => cmd(122, id, id, 1, 0, value);
const switchOn = (id: number): RmCommand => cmd(121, id, id, 0);
const switchOff = (id: number): RmCommand => cmd(121, id, id, 1);
const selfOn = (ch: string): RmCommand => cmd(123, ch, 0);

/** Transfer Player: direct designation; dir 0 keeps the facing; fade 0
 *  black, 1 white, 2 none. */
const transfer = (mapId: number, x: number, y: number, dir: number, fade: number): RmCommand =>
  cmd(201, 0, mapId, x, y, dir, fade);

const comment = (...lines: string[]): RmCommand[] => [cmd(108, lines[0]), ...lines.slice(1).map((l) => cmd(408, l))];
const script = (...lines: string[]): RmCommand[] => [cmd(355, lines[0]), ...lines.slice(1).map((l) => cmd(655, l))];

// --- movement routes ----------------------------------------------------------------

const mv = (code: number, ...parameters: unknown[]): RmMoveCommand =>
  parameters.length > 0 ? { code, indent: null, parameters } : { code, indent: null };

// Route command codes (Game_Character.ROUTE_*).
const R = {
  down: 1, left: 2, right: 3, up: 4, lowerL: 5, lowerR: 6, upperL: 7, upperR: 8,
  random: 9, toward: 10, away: 11, forward: 12, backward: 13, jump: 14, wait: 15,
  turnDown: 16, turnLeft: 17, turnRight: 18, turnUp: 19, turn90R: 20, turn90L: 21, turn180: 22,
  turnRandomLR: 23, turnRandom: 24, turnToward: 25, turnAway: 26, switchOn: 27, switchOff: 28,
  speed: 29, freq: 30, walkOn: 31, walkOff: 32, stepOn: 33, stepOff: 34, dirFixOn: 35, dirFixOff: 36,
  throughOn: 37, throughOff: 38, transparentOn: 39, transparentOff: 40, image: 41, opacity: 42,
  blend: 43, se: 44, script: 45,
} as const;

function route(moves: RmMoveCommand[], repeat: boolean, skippable: boolean, wait: boolean): RmMoveRoute {
  return { list: [...moves, { code: 0 }], repeat, skippable, wait };
}

/** Set Movement Route (characterId -1 player, 0 this event) with the 505
 *  lines the editor writes for display. */
const setRoute = (charId: number, r: RmMoveRoute): RmCommand[] => [
  cmd(205, charId, r),
  ...r.list.slice(0, -1).map((m) => cmd(505, m)),
];

// --- pages and events ------------------------------------------------------------------

const NO_CONDITIONS: RmPageConditions = {
  actorId: 1,
  actorValid: false,
  itemId: 1,
  itemValid: false,
  selfSwitchCh: "A",
  selfSwitchValid: false,
  switch1Id: 1,
  switch1Valid: false,
  switch2Id: 1,
  switch2Valid: false,
  variableId: 1,
  variableValid: false,
  variableValue: 0,
};

const whenSwitch = (id: number): Partial<RmPageConditions> => ({ switch1Id: id, switch1Valid: true });
const whenSelf = (ch: string): Partial<RmPageConditions> => ({ selfSwitchCh: ch, selfSwitchValid: true });
const whenItem = (id: number): Partial<RmPageConditions> => ({ itemId: id, itemValid: true });

interface PageSpec {
  list: RmCommand[];
  cond?: Partial<RmPageConditions>;
  /** A character sheet image, or a tile id. */
  image?: Partial<RmPageImage>;
  /** 0 action, 1 player touch, 2 event touch, 3 autorun, 4 parallel. */
  trigger?: number;
  /** Defaults to 1 (same as characters) with an image, else 0. */
  priority?: number;
  moveType?: number;
  route?: RmMoveRoute;
  speed?: number;
  freq?: number;
  through?: boolean;
  dirFix?: boolean;
  stepAnime?: boolean;
}

function page(s: PageSpec): RmEventPage {
  const image: RmPageImage = {
    tileId: 0,
    characterName: "",
    characterIndex: 0,
    direction: 2,
    pattern: s.image?.characterName ? 1 : 0,
    ...s.image,
  };
  const visible = image.characterName !== "" || image.tileId !== 0;
  return {
    conditions: { ...NO_CONDITIONS, ...s.cond },
    directionFix: s.dirFix ?? false,
    image,
    list: s.list,
    moveFrequency: s.freq ?? 3,
    moveRoute: s.route ?? { list: [{ code: 0, parameters: [] }], repeat: true, skippable: false, wait: false },
    moveSpeed: s.speed ?? 3,
    moveType: s.moveType ?? 0,
    priorityType: s.priority ?? (visible ? 1 : 0),
    stepAnime: s.stepAnime ?? false,
    through: s.through ?? false,
    trigger: s.trigger ?? 0,
    walkAnime: true,
  };
}

const event = (id: number, name: string, x: number, y: number, pages: RmEventPage[]): RmEvent => ({
  id,
  name,
  note: "",
  pages,
  x,
  y,
});

/** Events array: index 0 null, ids index the array, gaps stay null. */
function eventArray(events: RmEvent[]): (RmEvent | null)[] {
  const out: (RmEvent | null)[] = [null];
  for (const e of events) {
    while (out.length < e.id) out.push(null);
    out[e.id] = e;
  }
  return out;
}

// --- maps ---------------------------------------------------------------------------------

/** Tile ids: autotile kind (A1 0..15, A2 16..47, A3 48..79, A4 80..127),
 *  A5 index, B..E id. */
const auto = (kind: number): number => makeAutotileId(kind, 0);
const a5 = (index: number): number => TILE_ID_A5 + index;

class Grid {
  readonly data: number[];

  constructor(readonly w: number, readonly h: number) {
    this.data = new Array<number>(w * h * 6).fill(0);
  }

  set(z: number, x: number, y: number, id: number): void {
    this.data[(z * this.h + y) * this.w + x] = id;
  }

  /** Inclusive rectangle. */
  fill(z: number, x0: number, y0: number, x1: number, y1: number, id: number): void {
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) this.set(z, x, y, id);
  }

  points(z: number, id: number, pts: readonly (readonly [number, number])[]): void {
    for (const [x, y] of pts) this.set(z, x, y, id);
  }

  /** The data with every autotile shape as the editor stores it. */
  shaped(): number[] {
    return reshapeAutotiles(this.data, this.w, this.h);
  }
}

const audio = (name: string, volume = 90, pitch = 100, pan = 0): RmAudio => ({ name, pan, pitch, volume });
const SILENT = audio("", 90);

interface MapSpec {
  displayName: string;
  tilesetId: number;
  grid: Grid;
  events: RmEvent[];
  bgm?: RmAudio;
  bgs?: RmAudio;
  parallax?: {
    name: string;
    loopX: boolean;
    loopY: boolean;
    sx: number;
    sy: number;
    show: boolean;
  };
}

function rmMap(s: MapSpec): RmMap {
  const map: RmMap & Record<string, unknown> = {
    autoplayBgm: s.bgm !== undefined,
    autoplayBgs: s.bgs !== undefined,
    battleback1Name: "",
    battleback2Name: "",
    bgm: s.bgm ?? SILENT,
    bgs: s.bgs ?? SILENT,
    disableDashing: false,
    displayName: s.displayName,
    encounterList: [],
    encounterStep: 30,
    height: s.grid.h,
    note: "",
    parallaxLoopX: s.parallax?.loopX ?? false,
    parallaxLoopY: s.parallax?.loopY ?? false,
    parallaxName: s.parallax?.name ?? "",
    parallaxShow: s.parallax?.show ?? true,
    parallaxSx: s.parallax?.sx ?? 0,
    parallaxSy: s.parallax?.sy ?? 0,
    scrollType: 0,
    specifyBattleback: false,
    tilesetId: s.tilesetId,
    width: s.grid.w,
    data: s.grid.shaped(),
    events: eventArray(s.events),
  };
  return map;
}

const mapInfo = (id: number, name: string, order: number, parentId: number): RmMapInfo => ({
  expanded: false,
  id,
  name,
  order,
  parentId,
  scrollX: 0,
  scrollY: 0,
});

const mapFile = (id: number): string => `Map${String(id).padStart(3, "0")}.json`;

// --- tilesets ---------------------------------------------------------------------------------

/** Passage/attribute bits (Game_Map): low four bits block leaving/entering
 *  down 0x01, left 0x02, right 0x04, up 0x08; 0x10 star (drawn above
 *  characters, no effect on passage); 0x20 ladder; 0x40 bush; 0x80 counter
 *  (and the table look on A2); terrain tag in bits 12..15. */
const F = { block: 0x0f, down: 0x01, star: 0x10, bush: 0x40, counter: 0x80 } as const;

interface FlagSpec {
  /** By autotile kind (all 48 shape ids get the flag). */
  kinds?: Record<number, number>;
  a5?: Record<number, number>;
  b?: Record<number, number>;
}

/** The editor's flag table: A1, A3, A4 default to impassable, A2, A5 and
 *  B..E to passable, B id 0 (the empty tile) to star. */
function tilesetFlags(spec: FlagSpec): number[] {
  const flags = new Array<number>(8192).fill(0);
  flags[0] = F.star;
  for (let kind = 0; kind < 128; kind++) {
    const isA2 = kind >= 16 && kind < 48;
    const value = spec.kinds?.[kind] ?? (isA2 ? 0 : F.block);
    for (let shape = 0; shape < 48; shape++) flags[makeAutotileId(kind, shape)] = value;
  }
  for (const [i, v] of Object.entries(spec.a5 ?? {})) flags[a5(Number(i))] = v;
  for (const [n, v] of Object.entries(spec.b ?? {})) flags[Number(n)] = v;
  return flags;
}

const tileset = (id: number, name: string, mode: number, names: string[], flags: number[]): RmTileset => ({
  flags,
  id,
  mode,
  name,
  note: "",
  tilesetNames: names,
});

// --- database records (the importer reads a subset; the rest is what the
//     editors write) ----------------------------------------------------------------------------

const damageNone = { critical: false, elementId: 0, formula: "0", type: 0, variance: 20 };

function item(id: number, name: string, description: string, price: number, itypeId: number, iconIndex: number): RmItem {
  return {
    animationId: 0,
    consumable: itypeId === 1,
    damage: damageNone,
    description,
    effects: itypeId === 1 ? [{ code: 11, dataId: 0, value1: 0, value2: 30 }] : [],
    hitType: 0,
    iconIndex,
    id,
    itypeId,
    name,
    note: "",
    occasion: itypeId === 1 ? 0 : 3,
    price,
    repeats: 1,
    scope: itypeId === 1 ? 7 : 0,
    speed: 0,
    successRate: 100,
    tpGain: 0,
  } as RmItem;
}

function weapon(id: number, name: string, description: string, price: number, atk: number, wtypeId: number): RmItem {
  return {
    animationId: 1,
    description,
    etypeId: 1,
    iconIndex: 96 + wtypeId,
    id,
    name,
    note: "",
    params: [0, 0, atk, 0, 0, 0, 0, 0],
    price,
    traits: [{ code: 31, dataId: 1, value: 0 }, { code: 22, dataId: 0, value: 0 }],
    wtypeId,
  } as RmItem;
}

function armor(id: number, name: string, description: string, price: number, def: number): RmItem {
  return {
    atypeId: 1,
    description,
    etypeId: 4,
    iconIndex: 135,
    id,
    name,
    note: "",
    params: [0, 0, 0, def, 0, 0, 0, 0],
    price,
    traits: [],
  } as RmItem;
}

function actor(id: number, name: string, sheet: string, index: number, equips: number[]): RmActor {
  return {
    battlerName: "",
    characterIndex: index,
    characterName: sheet,
    classId: 1,
    equips,
    faceIndex: 0,
    faceName: "",
    id,
    initialLevel: 1,
    maxLevel: 99,
    name,
    nickname: "",
    note: "",
    profile: "",
    traits: [],
  } as RmActor;
}

/** One class with linear parameter curves (levels 0..99). */
function classes(name: string): unknown[] {
  const curve = (base: number, step: number): number[] =>
    Array.from({ length: 100 }, (_, lv) => base + step * lv);
  return [
    null,
    {
      expParams: [30, 20, 30, 30],
      id: 1,
      learnings: [],
      name,
      note: "",
      params: [curve(400, 40), curve(60, 6), curve(16, 2), curve(14, 2), curve(12, 2), curve(12, 2), curve(14, 2), curve(10, 1)],
      traits: [
        { code: 23, dataId: 0, value: 1 },
        { code: 22, dataId: 0, value: 0.95 },
        { code: 41, dataId: 1, value: 0 },
        { code: 51, dataId: 1, value: 0 },
        { code: 51, dataId: 2, value: 0 },
        { code: 52, dataId: 1, value: 0 },
      ],
    },
  ];
}

const skills = (): unknown[] => [
  null,
  {
    animationId: -1,
    damage: { critical: true, elementId: -1, formula: "a.atk * 4 - b.def * 2", type: 1, variance: 20 },
    description: "",
    effects: [{ code: 21, dataId: 0, value1: 1, value2: 0 }],
    hitType: 1,
    iconIndex: 76,
    id: 1,
    message1: " attacks!",
    message2: "",
    mpCost: 0,
    name: "Attack",
    note: "",
    occasion: 1,
    repeats: 1,
    requiredWtypeId1: 0,
    requiredWtypeId2: 0,
    scope: 1,
    speed: 0,
    stypeId: 0,
    successRate: 100,
    tpCost: 0,
    tpGain: 10,
  },
];

const states = (): unknown[] => [
  null,
  {
    autoRemovalTiming: 0,
    chanceByDamage: 100,
    iconIndex: 1,
    id: 1,
    maxTurns: 1,
    message1: " has fallen!",
    message2: " is slain!",
    message3: "",
    message4: " revives!",
    minTurns: 1,
    motion: 3,
    name: "Knockout",
    note: "State #1 is the knockout state.",
    overlay: 0,
    priority: 100,
    releaseByDamage: false,
    removeAtBattleEnd: false,
    removeByDamage: false,
    removeByRestriction: false,
    removeByWalking: false,
    restriction: 4,
    stepsToRemove: 100,
    traits: [],
  },
];

// --- System.json -----------------------------------------------------------------------------------

const TERMS = {
  basic: ["Level", "Lv", "HP", "HP", "MP", "MP", "TP", "TP", "EXP", "EXP"],
  commands: [
    "Fight", "Escape", "Attack", "Guard", "Item", "Skill", "Equip", "Status", "Formation", "Save",
    "Game End", "Options", "Weapon", "Armor", "Key Item", "Equip", "Optimize", "Clear", "New Game",
    "Continue", null, "To Title", "Cancel", null, "Buy", "Sell",
  ],
  messages: {
    actionFailure: "There was no effect on %1!",
    actorDamage: "%1 took %2 damage!",
    alwaysDash: "Always Dash",
    bgmVolume: "BGM Volume",
    bgsVolume: "BGS Volume",
    defeat: "%1 was defeated.",
    emerge: "%1 emerged!",
    escapeFailure: "However, it was unable to escape!",
    escapeStart: "%1 has started to escape!",
    file: "File",
    meVolume: "ME Volume",
    obtainGold: "%1\\G found!",
    obtainItem: "%1 found!",
    possession: "Possession",
    saveMessage: "Save to which file?",
    seVolume: "SE Volume",
    victory: "%1 was victorious!",
  },
  params: ["Max HP", "Max MP", "Attack", "Defense", "M.Attack", "M.Defense", "Agility", "Luck", "Hit", "Evasion"],
};

const vehicle = { bgm: SILENT, characterIndex: 0, characterName: "", startMapId: 0, startX: 0, startY: 0 };

const names = (size: number, named: Record<number, string>): string[] =>
  Array.from({ length: size + 1 }, (_, i) => named[i] ?? "");

interface SystemSpec {
  flavor: "MV" | "MZ";
  title: string;
  start: [mapId: number, x: number, y: number];
  switches: Record<number, string>;
  variables: Record<number, string>;
  versionId: number;
  partyMembers: number[];
}

function system(s: SystemSpec): RmSystem {
  const common: Record<string, unknown> = {
    airship: vehicle,
    armorTypes: ["", "Clothing"],
    attackMotions: [
      { type: 0, weaponImageId: 0 },
      { type: 1, weaponImageId: 1 },
      { type: 1, weaponImageId: 2 },
    ],
    battleBgm: SILENT,
    battleback1Name: "",
    battleback2Name: "",
    battlerHue: 0,
    battlerName: "",
    boat: vehicle,
    currencyUnit: "G",
    defeatMe: SILENT,
    editMapId: s.start[0],
    elements: ["", "Physical"],
    equipTypes: ["", "Weapon", "Shield", "Head", "Body", "Accessory"],
    gameTitle: s.title,
    gameoverMe: SILENT,
    locale: "en_US",
    magicSkills: [],
    menuCommands: [true, true, true, true, true, true],
    optDisplayTp: true,
    optDrawTitle: true,
    optExtraExp: false,
    optFloorDeath: false,
    optFollowers: true,
    optSideView: false,
    optSlipDeath: false,
    optTransparent: false,
    partyMembers: s.partyMembers,
    ship: vehicle,
    skillTypes: ["", "Craft"],
    sounds: Array.from({ length: 24 }, () => SILENT),
    startMapId: s.start[0],
    startX: s.start[1],
    startY: s.start[2],
    switches: names(20, s.switches),
    terms: TERMS,
    testBattlers: [{ actorId: 1, equips: [1, 0, 0, 1, 0], level: 1 }],
    testTroopId: 1,
    title1Name: "",
    title2Name: "",
    titleBgm: SILENT,
    variables: names(20, s.variables),
    versionId: s.versionId,
    victoryMe: SILENT,
    weaponTypes: ["", "Staff", "Sword"],
    windowTone: [0, 0, 0, 0],
  };
  if (s.flavor === "MZ") {
    Object.assign(common, {
      advanced: {
        fallbackFonts: "Verdana, sans-serif",
        fontSize: 16,
        gameId: 30111986,
        mainFontFilename: "",
        numberFontFilename: "",
        picturesUpperLimit: 100,
        screenHeight: 272,
        screenScale: 1,
        screenWidth: 480,
        uiAreaHeight: 272,
        uiAreaWidth: 480,
        windowOpacity: 192,
      },
      battleSystem: 0,
      faceSize: 144,
      iconSize: 32,
      itemCategories: [true, true, true, true],
      optAutosave: false,
      optKeyItemsNumber: false,
      optMessageSkip: true,
      optSplashScreen: false,
      tileSize: 16,
      titleCommandWindow: { background: 0, offsetX: 0, offsetY: 0 },
    });
  }
  return common as unknown as RmSystem;
}

// --- shared character art ---------------------------------------------------------------------

const skin = rgb("#f0c8a0");
const look = (hair: string, top: string, bottom: string) => ({ skin, hair: rgb(hair), top: rgb(top), bottom: rgb(bottom) });

function writeData(files: Files, root: string, name: string, text: string): void {
  files.set(`${root}/data/${name}`, text);
}

// =====================================================================================================
// Project A: hollow-mz
// =====================================================================================================

const HOLLOW = "hollow-mz";

// Switches and variables.
const S_QUEST = 1;
const S_GATE = 2;
const S_IN_CAVE = 4;
const S_BOSS_DOWN = 10;
const S_PEACE = 11;
const V_QUEST = 1;
const V_LUCK = 2;
const V_BONUS = 3;
const V_REWARD = 5;
const V_ESCAPES = 6;
const V_DEFEATS = 7;
const V_TICKS = 9;

// Database ids.
const I_POTION = 1;
const I_PASS = 2;

// Hollow_B tiles.
const HB = {
  treeTop: 1, rock: 2, fence: 3, gate: 4, caveMouth: 5, cliff: 6, flowers: 7, pot: 8,
  treeTrunk: 9, barrel: 10, sign: 11, bookshelf: 12, crate: 13, bones: 15, stalagmite: 16,
  crystal: 17, window: 18,
} as const;

// Autotile kinds and A5 indices.
const K = {
  pond: 0, deep: 1, caveWater: 4, waterfall: 5,
  grass: 16, dirt: 17, tallGrass: 18, stone: 19, caveDirt: 20, carpet: 21, snow: 22, table: 23,
  roof: 48, roofBlue: 49, wall: 56, wallStone: 57,
  houseTop: 80, caveTop: 81, houseSide: 88, caveSide: 89,
} as const;
const H5 = { void: 0, wood: 1, caveFloor: 2, doormat: 3, counter: 4, stone: 5, rug: 6, darkCave: 7 } as const;

const HOLLOW_SHEETS = ["Hollow_A1", "Hollow_A2", "Hollow_A3", "Hollow_A4", "Hollow_A5", "Hollow_B", "", "", ""];

function hollowFlags(): number[] {
  return tilesetFlags({
    kinds: {
      [K.tallGrass]: F.bush | (1 << 12),
      [K.table]: F.counter | F.block,
    },
    a5: { [H5.void]: F.block, [H5.counter]: F.counter | F.block },
    b: {
      [HB.treeTop]: F.star,
      [HB.treeTrunk]: F.block,
      [HB.rock]: F.block,
      [HB.fence]: F.down,
      [HB.gate]: F.block,
      [HB.cliff]: F.block,
      [HB.pot]: F.block,
      [HB.barrel]: F.block,
      [HB.sign]: F.block,
      [HB.bookshelf]: F.block,
      [HB.crate]: F.block,
      [HB.stalagmite]: F.block,
      [HB.crystal]: F.block,
      [HB.window]: F.star,
    },
  });
}

function hollowMaterials() {
  const a1 = (kind: number): Material => {
    switch (kind) {
      case K.pond: return material(rgb("#3a78c8"), "waves", 100);
      case K.deep: return material(rgb("#24509a"), "waves", 101);
      case 2: return material(rgb("#3a78c8"), "speckle", 102);
      case 3: return material(rgb("#24509a"), "rock", 103);
      case K.caveWater: return material(rgb("#2a6a78"), "waves", 104);
      case K.waterfall: return material(rgb("#6ab0d8"), "streaks", 105);
      default: return hueMaterial(kind, kind % 2 === 0 ? "waves" : "streaks");
    }
  };
  const a2 = (kind: number): Material => {
    switch (kind) {
      case K.grass: return material(rgb("#5aa040"), "grass", 116);
      case K.dirt: return material(rgb("#b08850"), "speckle", 117);
      case K.tallGrass: return material(rgb("#3c8a34"), "grass", 118);
      case K.stone: return material(rgb("#9a9a90"), "checker", 119);
      case K.caveDirt: return material(rgb("#6a5a4a"), "rock", 120);
      case K.carpet: return material(rgb("#a03040"), "weave", 121);
      case K.snow: return material(rgb("#e8eef4"), "speckle", 122);
      case K.table: return material(rgb("#8a5a30"), "planks", 123);
      default: return hueMaterial(kind, "speckle");
    }
  };
  const a3 = (kind: number): Material => {
    switch (kind) {
      case K.roof: return material(rgb("#b04030"), "shingles", 148);
      case K.roofBlue: return material(rgb("#3a5aa0"), "shingles", 149);
      case K.wall: return material(rgb("#e0d0b0"), "bricks", 156);
      case K.wallStone: return material(rgb("#a0a0a0"), "bricks", 157);
      default: return hueMaterial(kind, Math.floor(kind / 8) % 2 === 0 ? "shingles" : "bricks");
    }
  };
  const a4 = (kind: number): Material => {
    switch (kind) {
      case K.houseTop: return material(rgb("#5a4030"), "planks", 180);
      case K.caveTop: return material(rgb("#4a4440"), "rock", 181);
      case K.houseSide: return material(rgb("#d8c8a0"), "weave", 188);
      case K.caveSide: return material(rgb("#6a625a"), "rock", 189);
      default: return hueMaterial(kind, Math.floor(kind / 8) % 2 === 0 ? "speckle" : "bricks");
    }
  };
  return { a1, a2, a3, a4 };
}

function hollowA5(i: number): TileDraw {
  switch (i) {
    case H5.void: return plainTile(material(rgb("#101010"), "plain", 0));
    case H5.wood: return plainTile(material(rgb("#a07040"), "planks", 201));
    case H5.caveFloor: return plainTile(material(rgb("#5a524a"), "rock", 202));
    case H5.doormat: return plainTile(material(rgb("#7a3a2a"), "weave", 203));
    case H5.counter: return (c, x0, y0) => {
      const m = material(rgb("#8a5a30"), "planks", 204);
      c.paint(x0, y0, TS, TS, (x, y) => texel(m, x, y));
      c.rect(x0, y0, TS, 4, m.light);
      c.rect(x0, y0 + 4, TS, 1, m.edge);
      c.rect(x0, y0 + TS - 1, TS, 1, m.edge);
    };
    case H5.stone: return plainTile(material(rgb("#8a8a84"), "checker", 205));
    case H5.rug: return plainTile(material(rgb("#3a5a9a"), "weave", 206));
    case H5.darkCave: return plainTile(material(rgb("#3a342e"), "rock", 207));
    default: return plainTile(hueMaterial(i + 200, "checker"));
  }
}

function hollowB(): Map<number, TileDraw> {
  const leaf = rgb("#2f7a2a");
  const leafDark = shade(leaf, 0.6);
  const bark = rgb("#6a4424");
  const stone = material(rgb("#8a8680"), "rock", 300);
  const wood = material(rgb("#9a6a3a"), "planks", 301);
  const t = new Map<number, TileDraw>();
  t.set(HB.treeTop, (c, x, y) => {
    c.rect(x + 3, y + 3, 10, 13, leafDark);
    c.rect(x + 2, y + 5, 12, 11, leafDark);
    c.rect(x + 4, y + 4, 8, 12, leaf);
    c.rect(x + 3, y + 6, 10, 10, leaf);
    c.rect(x + 5, y + 6, 2, 2, shade(leaf, 1.4));
  });
  t.set(HB.treeTrunk, (c, x, y) => {
    c.rect(x + 2, y, 12, 7, leafDark);
    c.rect(x + 3, y, 10, 6, leaf);
    c.rect(x + 6, y + 7, 4, 8, bark);
    c.rect(x + 5, y + 14, 6, 2, shade(bark, 0.7));
  });
  t.set(HB.rock, (c, x, y) => {
    c.rect(x + 2, y + 5, 12, 10, stone.edge);
    c.paint(x + 3, y + 6, 10, 8, (px, py) => texel(stone, px, py));
  });
  t.set(HB.fence, (c, x, y) => {
    c.rect(x, y + 9, TS, 2, wood.base);
    c.rect(x, y + 13, TS, 2, wood.base);
    c.rect(x + 1, y + 7, 2, 9, wood.edge);
    c.rect(x + 13, y + 7, 2, 9, wood.edge);
  });
  t.set(HB.gate, (c, x, y) => {
    c.rect(x, y + 3, TS, 13, wood.edge);
    for (let i = 0; i < 4; i++) c.rect(x + 1 + i * 4, y + 4, 2, 12, wood.base);
    c.rect(x, y + 7, TS, 2, wood.dark);
    c.rect(x, y + 12, TS, 2, wood.dark);
  });
  t.set(HB.caveMouth, (c, x, y) => {
    c.paint(x, y, TS, TS, (px, py) => texel(stone, px, py));
    c.rect(x + 3, y + 3, 10, 13, rgb("#141010"));
    c.rect(x + 4, y + 2, 8, 1, rgb("#141010"));
  });
  t.set(HB.cliff, (c, x, y) => {
    c.paint(x, y, TS, TS, (px, py) => texel(stone, px, py));
    c.rect(x, y + TS - 2, TS, 2, stone.edge);
  });
  t.set(HB.flowers, (c, x, y) => {
    for (const [fx, fy, col] of [[3, 4, "#f0e040"], [10, 3, "#f06080"], [6, 10, "#ffffff"], [12, 11, "#f0e040"]] as const) {
      c.rect(x + fx, y + fy, 2, 2, rgb(col));
      c.set(x + fx, y + fy + 2, leafDark);
    }
  });
  t.set(HB.pot, (c, x, y) => {
    c.rect(x + 4, y + 5, 8, 10, rgb("#6a3a20"));
    c.rect(x + 5, y + 6, 6, 8, rgb("#b0602a"));
    c.rect(x + 5, y + 4, 6, 2, rgb("#6a3a20"));
  });
  t.set(HB.barrel, (c, x, y) => {
    c.rect(x + 3, y + 3, 10, 12, wood.edge);
    c.paint(x + 4, y + 4, 8, 10, (px, py) => texel(wood, py, px));
    c.rect(x + 3, y + 6, 10, 1, rgb("#505050"));
    c.rect(x + 3, y + 11, 10, 1, rgb("#505050"));
  });
  t.set(HB.sign, (c, x, y) => {
    c.rect(x + 7, y + 8, 2, 8, wood.edge);
    c.rect(x + 2, y + 2, 12, 7, wood.edge);
    c.rect(x + 3, y + 3, 10, 5, wood.light);
    c.rect(x + 4, y + 5, 8, 1, wood.edge);
  });
  t.set(HB.bookshelf, (c, x, y) => {
    c.rect(x, y, TS, TS, wood.edge);
    for (let r = 0; r < 3; r++) {
      c.rect(x + 1, y + 1 + r * 5, 14, 4, shade(wood.base, 0.5));
      for (let b = 0; b < 6; b++) c.rect(x + 2 + b * 2, y + 2 + r * 5, 1, 3, hsl((b * 70 + r * 40) % 360, 50, 45));
    }
  });
  t.set(HB.crate, (c, x, y) => {
    c.rect(x + 2, y + 3, 12, 12, wood.edge);
    c.paint(x + 3, y + 4, 10, 10, (px, py) => texel(wood, px, py));
    c.rect(x + 3, y + 8, 10, 1, wood.edge);
  });
  t.set(HB.bones, (c, x, y) => {
    c.rect(x + 3, y + 9, 8, 2, rgb("#e8e0d0"));
    c.rect(x + 2, y + 8, 2, 4, rgb("#e8e0d0"));
    c.rect(x + 10, y + 8, 2, 4, rgb("#e8e0d0"));
    c.rect(x + 8, y + 4, 3, 3, rgb("#e8e0d0"));
  });
  t.set(HB.stalagmite, (c, x, y) => {
    for (let r = 0; r < 12; r++) {
      const half = 1 + Math.floor(r / 2);
      c.rect(x + 8 - half, y + 3 + r, half * 2, 1, r === 11 ? stone.edge : stone.base);
    }
  });
  t.set(HB.crystal, (c, x, y) => {
    for (let r = 0; r < 10; r++) {
      const half = r < 5 ? 1 + r : 10 - r;
      c.rect(x + 8 - half, y + 3 + r, half * 2, 1, r < 5 ? rgb("#a0e8f0") : rgb("#50a0c0"));
    }
  });
  t.set(HB.window, (c, x, y) => {
    c.rect(x + 3, y + 3, 10, 9, wood.edge);
    c.rect(x + 4, y + 4, 8, 7, rgb("#a0d0f0"));
    c.rect(x + 7, y + 4, 1, 7, wood.edge);
    c.rect(x + 4, y + 7, 8, 1, wood.edge);
  });
  return t;
}

/** A standard 16-column IconSet with only the fixture database's cells
 * occupied. Each motif is original integer-pixel art; the importer halves
 * the 32 px source cells to the kit's 16 px item sprites. */
function fixtureIconSet(): Canvas {
  const c = new Canvas(16 * 32, 13 * 32);
  const at = (index: number): [number, number] => [(index % 16) * 32, Math.floor(index / 16) * 32];
  const tile = (index: number, base: ReturnType<typeof rgb>, accent: ReturnType<typeof rgb>): [number, number] => {
    const [x, y] = at(index);
    c.rect(x + 6, y + 6, 20, 20, shade(base, 0.45));
    c.rect(x + 8, y + 8, 16, 16, base);
    c.frame(x + 8, y + 8, 16, 16, accent);
    return [x, y];
  };

  // State and skill marks (not imported as inventory, but keep every
  // referenced database icon visibly self-contained).
  let [x, y] = tile(1, rgb("#8050b0"), rgb("#e0c8ff"));
  c.rect(x + 14, y + 10, 4, 12, rgb("#fff0a0"));
  c.rect(x + 10, y + 14, 12, 4, rgb("#fff0a0"));
  [x, y] = tile(76, rgb("#d07030"), rgb("#ffe0a0"));
  c.rect(x + 14, y + 9, 4, 14, rgb("#fff8d0"));
  c.rect(x + 10, y + 13, 12, 6, rgb("#fff8d0"));

  // Staff, sword and vest.
  [x, y] = tile(97, rgb("#704828"), rgb("#e0b060"));
  for (let p = 0; p < 16; p += 2) c.rect(x + 8 + p, y + 22 - p, 4, 4, rgb("#e0b060"));
  c.rect(x + 18, y + 8, 6, 6, rgb("#70d090"));
  [x, y] = tile(98, rgb("#405070"), rgb("#d8e8ff"));
  for (let p = 0; p < 14; p += 2) c.rect(x + 10 + p, y + 20 - p, 4, 4, rgb("#f0f4ff"));
  c.rect(x + 8, y + 20, 10, 4, rgb("#d0a040"));
  [x, y] = tile(135, rgb("#506080"), rgb("#d0d8e8"));
  c.rect(x + 10, y + 9, 12, 5, rgb("#d0d8e8"));
  c.rect(x + 8, y + 13, 16, 11, rgb("#a8b8d0"));
  c.rect(x + 14, y + 13, 4, 11, rgb("#506080"));

  // Potion and cave-pass/ticket.
  [x, y] = tile(176, rgb("#803050"), rgb("#ffc0d0"));
  c.rect(x + 13, y + 8, 6, 5, rgb("#e8d8c0"));
  c.rect(x + 10, y + 13, 12, 11, rgb("#e05070"));
  c.rect(x + 12, y + 15, 8, 4, rgb("#ff90b0"));
  [x, y] = tile(195, rgb("#806020"), rgb("#ffe080"));
  c.rect(x + 8, y + 11, 16, 10, rgb("#f0c858"));
  c.frame(x + 8, y + 11, 16, 10, rgb("#fff0a0"));
  c.rect(x + 15, y + 11, 2, 10, rgb("#806020"));
  return c;
}

function hollowArt(files: Files): void {
  const m = hollowMaterials();
  const img = (path: string, canvas: Canvas) => files.set(`${HOLLOW}/img/${path}`, canvas.png());
  img("tilesets/Hollow_A1.png", sheetA1(m.a1));
  img("tilesets/Hollow_A2.png", sheetA2(m.a2));
  img("tilesets/Hollow_A3.png", sheetA3(m.a3));
  img("tilesets/Hollow_A4.png", sheetA4(m.a4));
  img("tilesets/Hollow_A5.png", sheetA5(hollowA5));
  img("tilesets/Hollow_B.png", sheetB(hollowB()));
  img(
    "characters/People.png",
    characterSheet([
      person(look("#6a3a1a", "#3a8a4a", "#3a3a5a")), // 0 Wren
      person(look("#e8e8e8", "#6a3a8a", "#4a2a5a")), // 1 elder
      person(look("#2a2a2a", "#e0e0d0", "#6a4a2a")), // 2 shopkeeper
      person(look("#8a6a3a", "#8a96a8", "#4a4a5a")), // 3 guard
      person(look("#a05a2a", "#8a6a3a", "#3a5a3a")), // 4 Moss
      person(look("#d0a040", "#3a6ac8", "#2a3a6a")), // 5 villager
      person(look("#3a2a1a", "#c85a3a", "#5a3a2a")), // 6
      person(look("#5a5a5a", "#5a8a8a", "#2a2a2a")), // 7
    ]),
  );
  img("characters/!Things.png", characterSheet([chest(rgb("#9a6030"), rgb("#e0c060")), door(rgb("#7a4a2a"))]));
  img("characters/$Golem.png", singleSheet(golem(rgb("#7a746c"), rgb("#f0a030"))));
  img("system/Balloon.png", balloonSheet());
  img("system/IconSet.png", fixtureIconSet());
  // Front-view battler for the placeholder battle (Enemies.json).
  const battler = new Canvas(64, 64);
  const rock = material(rgb("#7a746c"), "rock", 400);
  battler.rect(8, 6, 48, 56, rock.edge);
  battler.paint(10, 8, 44, 52, (x, y) => texel(rock, x, y));
  battler.rect(20, 24, 8, 4, rgb("#f0a030"));
  battler.rect(36, 24, 8, 4, rgb("#f0a030"));
  img("enemies/Golem.png", battler);
}

// --- Hollow maps ----------------------------------------------------------------------------------------

const SE = {
  chime: audio("hollow-chime"),
  door: audio("hollow-door"),
  steps: audio("hollow-steps", 80),
  drip: audio("hollow-drip", 60),
  gate: audio("hollow-gate"),
  chest: audio("hollow-chest"),
};

function hollowVillage(): RmMap {
  const g = new Grid(24, 16);
  g.fill(0, 0, 0, 23, 15, auto(K.grass));
  // Dirt: the plaza, the lane to the house door, the road east and the
  // path north through the gate to the cave mouth.
  g.fill(0, 10, 8, 12, 10, auto(K.dirt));
  g.fill(0, 11, 6, 11, 7, auto(K.dirt));
  g.fill(0, 13, 10, 19, 10, auto(K.dirt));
  g.fill(0, 19, 0, 19, 9, auto(K.dirt));
  // Pond (animated A1), an irregular blob.
  g.fill(0, 2, 10, 5, 13, auto(K.pond));
  g.set(0, 2, 10, auto(K.grass));
  g.set(0, 5, 13, auto(K.grass));
  g.fill(5, 2, 10, 5, 13, 1);
  g.set(5, 2, 10, 0);
  g.set(5, 5, 13, 0);
  // Tall grass (bush flag, terrain tag 1).
  g.fill(0, 20, 12, 22, 14, auto(K.tallGrass));
  // House: A3 roof over A3 wall; the door is an event at (11, 5).
  g.fill(0, 9, 2, 13, 3, auto(K.roof));
  g.fill(0, 9, 4, 13, 5, auto(K.wall));
  g.points(2, HB.window, [[10, 4], [12, 4]]);
  g.fill(4, 14, 2, 14, 5, 0b0101); // shadow on the left quarters east of the house
  // North enclosure: cliff with the cave mouth, a tree wall on the west,
  // a fence (blocks the tile's bottom edge only) with the gate at x 19.
  for (let x = 16; x <= 23; x++) if (x !== 19) g.set(2, x, 0, HB.cliff);
  g.set(2, 19, 0, HB.caveMouth);
  for (let y = 1; y <= 6; y++) g.set(2, 15, y, HB.treeTrunk);
  for (let y = 0; y <= 5; y++) g.set(3, 15, y, HB.treeTop);
  for (const x of [16, 17, 18, 20, 21, 22, 23]) g.set(2, x, 6, HB.fence);
  // Free-standing trees: trunk on z 2, star-flagged top on z 3 above it.
  for (const [x, y] of [[6, 5], [3, 7], [22, 8]] as const) {
    g.set(2, x, y, HB.treeTrunk);
    g.set(3, x, y - 1, HB.treeTop);
  }
  g.points(2, HB.rock, [[8, 13], [16, 12]]);
  g.points(2, HB.flowers, [[7, 8], [8, 11], [14, 13]]);
  g.set(2, 8, 7, HB.sign);

  const elderPage1 = page({
    image: { characterName: "People", characterIndex: 1 },
    list: list(
      mzText("Elder", "Ah, \\N[1]. A golem has woken in the cave", "and the north gate is barred. Will you help?"),
      choices(
        ["I'll help", "Not now"],
        -2,
        0,
        [
          [
            setVar(V_QUEST, 1),
            cmd(122, V_LUCK, V_LUCK, 0, 2, 1, 6),
            setVar(V_BONUS, 10),
            cmd(122, V_BONUS, V_BONUS, 1, 1, V_LUCK),
            switchOn(S_QUEST),
            mzText(
              "Elder",
              "Bless you. Your luck today reads \\V[2].",
              "Take the \\C[2]Cave Pass\\C[0] from the chest in my",
              "house, and keep the 50\\G beside it.",
            ),
          ],
          [mzText("Elder", "Then rest a while. The golem will wait.")],
        ],
        [mzText("Elder", "Hm? Speak up, child.")],
      ),
      ifThen(ifVar(V_QUEST, 1, 1), [mzText("Elder", "My house is just north of the plaza.")]),
    ),
  });
  const elderPage2 = page({
    cond: whenSwitch(S_QUEST),
    image: { characterName: "People", characterIndex: 1 },
    list: list(
      ifThen(
        ifSwitch(S_BOSS_DOWN),
        [
          mzText("Elder", "The golem is dust! Hollow is safe, \\N[1].", "\\C[3]Thank you.\\C[0]"),
          switchOn(S_PEACE),
          setVar(V_QUEST, 3),
        ],
        [
          ifThen(
            ifItem(I_PASS),
            [mzText("Elder", "Show the pass to the guard by the north gate.")],
            [mzText("Elder", "The chest is in my house, north of the plaza.")],
          ),
        ],
      ),
    ),
  });

  const doorRoute = route(
    [mv(R.dirFixOff), mv(R.turnLeft), mv(R.wait, 3), mv(R.turnRight), mv(R.wait, 3), mv(R.turnUp), mv(R.dirFixOn)],
    false,
    false,
    true,
  );

  const guardPage2 = page({
    cond: whenItem(I_PASS),
    image: { characterName: "People", characterIndex: 3 },
    list: list(
      mzText("Guard", "The elder's pass! Very well."),
      ifThen(
        ifItem(I_PASS),
        [
          cmd(129, 2, 0, true),
          mzText("Guard", "Take \\N[2] along; the cave is no place to go alone.", "Want to call \\N[2] something else?"),
          choices(["Rename", "Keep"], 1, 1, [[cmd(303, 2, 8)], []]),
          switchOn(S_GATE),
          setRoute(0, route([mv(R.turnUp), mv(R.wait, 20), mv(R.turnDown)], false, true, true)),
          cmd(250, SE.gate),
          mzText("Guard", "The gate is open. Mind the golem, \\N[1]."),
          selfOn("A"),
        ],
        [mzText("Guard", "...You had it a moment ago?")],
      ),
    ),
  });

  const bellLoop = loop(
    cmd(230, 60),
    addVar(V_TICKS, 1),
    ifThen(ifVar(V_TICKS, 1, 5), [selfOn("B"), cmd(113)]),
  );

  const events = [
    event(1, "Intro", 0, 15, [
      page({
        trigger: 3,
        list: list(
          comment("Opening: rain, a plugin call and a script line.", "Runs once (self switch A)."),
          cmd(236, "rain", 3, 60, false),
          cmd(357, "HollowLog", "mark", "Mark Chapter", { chapter: "1", label: "Arrival" }),
          cmd(657, "Chapter = 1"),
          cmd(657, "Label = Arrival"),
          script("const tag = \"hollow-intro\";", "$gameTemp.hollowTag = tag;"),
          mzText("", "Rain drums on the roofs of Hollow."),
          cmd(230, 30),
          cmd(236, "none", 0, 60, false),
          selfOn("A"),
        ),
      }),
      page({ cond: whenSelf("A"), list: list() }),
    ]),
    event(2, "Elder", 13, 9, [elderPage1, elderPage2]),
    event(3, "House Door", 11, 5, [
      page({
        image: { characterName: "!Things", characterIndex: 1 },
        dirFix: true,
        trigger: 1,
        list: list(cmd(250, SE.door), setRoute(0, doorRoute), transfer(2, 6, 8, 8, 0)),
      }),
    ]),
    event(4, "Gate", 19, 6, [
      page({ image: { tileId: HB.gate }, list: list(mzText("", "The gate is barred from the inside.")) }),
      page({ cond: whenSwitch(S_GATE), priority: 0, list: list() }),
    ]),
    event(5, "Guard", 18, 7, [
      page({
        image: { characterName: "People", characterIndex: 3 },
        list: list(mzText("Guard", "Halt! Only holders of the \\C[2]Cave Pass\\C[0] may pass.")),
      }),
      guardPage2,
      page({
        cond: whenSelf("A"),
        image: { characterName: "People", characterIndex: 3 },
        list: list(mzText("Guard", "Beware the golem, \\N[1].")),
      }),
    ]),
    event(6, "To Cave", 19, 0, [
      page({
        trigger: 2,
        list: list(switchOn(S_IN_CAVE), cmd(250, SE.steps), transfer(3, 10, 13, 8, 1)),
      }),
    ]),
    event(7, "Villager", 3, 3, [
      page({
        image: { characterName: "People", characterIndex: 5 },
        moveType: 3,
        route: route(
          [mv(R.left), mv(R.left), mv(R.wait, 30), mv(R.right), mv(R.right), mv(R.wait, 30)],
          true,
          false,
          false,
        ),
        list: list(mzText("Villager", "Rain again. Good for the pond, at least.")),
      }),
    ]),
    // Event 8 was deleted; the array keeps a null there.
    event(9, "Bell", 0, 14, [
      page({ trigger: 4, list: list(bellLoop) }),
      page({ cond: whenSelf("B"), list: list() }),
    ]),
  ];

  return rmMap({
    displayName: "Hollow",
    tilesetId: 1,
    grid: g,
    events,
    bgm: audio("hollow-theme", 70),
  });
}

function hollowHouse(): RmMap {
  const g = new Grid(13, 10);
  g.fill(0, 0, 0, 12, 9, auto(K.houseTop));
  g.fill(0, 1, 1, 11, 2, auto(K.houseSide));
  g.fill(0, 1, 3, 11, 8, a5(H5.wood));
  g.set(0, 6, 9, a5(H5.doormat));
  // The counter frames the shopkeeper, with a service opening at (9,5).
  // RPG Maker can trigger events across counter tiles, but that unrelated
  // interaction rule is intentionally reported as degraded by this importer.
  g.points(0, a5(H5.counter), [[8, 3], [8, 4], [8, 5], [10, 5], [11, 5]]);
  // A2 table with the table/counter flag.
  g.fill(0, 2, 6, 3, 7, auto(K.table));
  g.points(2, HB.window, [[3, 1], [9, 1]]);
  g.points(2, HB.bookshelf, [[1, 3], [2, 3]]);
  g.set(2, 11, 3, HB.crate);
  g.set(2, 11, 8, HB.pot);
  g.set(2, 1, 8, HB.barrel);

  const chestOpen = route(
    [mv(R.dirFixOff), mv(R.turnLeft), mv(R.wait, 3), mv(R.turnRight), mv(R.wait, 3), mv(R.turnUp), mv(R.dirFixOn)],
    false,
    false,
    true,
  );
  const events = [
    event(1, "Exit", 6, 9, [page({ trigger: 1, list: list(cmd(250, SE.door), transfer(1, 11, 6, 2, 0)) })]),
    event(2, "Chest", 6, 3, [
      page({
        image: { characterName: "!Things", characterIndex: 0 },
        dirFix: true,
        list: list(
          ifThen(
            ifSwitch(S_QUEST),
            [
              cmd(250, SE.chest),
              setRoute(0, chestOpen),
              cmd(126, I_POTION, 0, 0, 2),
              cmd(126, I_PASS, 0, 0, 1),
              cmd(125, 0, 0, 50),
              setVar(V_QUEST, 2),
              mzText("", "Found \\C[3]2 Potions\\C[0], the Cave Pass and 50\\G!"),
              cmd(117, 1),
              selfOn("A"),
            ],
            [mzText("", "The lid is stuck fast. Perhaps the elder knows.")],
          ),
        ),
      }),
      page({
        cond: whenSelf("A"),
        image: { characterName: "!Things", characterIndex: 0, direction: 8 },
        dirFix: true,
        list: list(mzText("", "Empty.")),
      }),
    ]),
    event(3, "Shopkeeper", 9, 4, [
      page({
        image: { characterName: "People", characterIndex: 2 },
        list: list(
          mzText("Shopkeeper", "Welcome! Potions, blades, a warm vest."),
          shop([[0, I_POTION, 0, 0], [1, 2, 1, 80], [2, 1, 0, 0]], false),
          mzText("Shopkeeper", "Come again!"),
        ),
      }),
    ]),
  ];
  return rmMap({ displayName: "Elder's House", tilesetId: 2, grid: g, events });
}

function hollowCave(): RmMap {
  const g = new Grid(20, 15);
  g.fill(0, 0, 0, 19, 14, auto(K.caveTop));
  g.fill(0, 1, 1, 18, 2, auto(K.caveSide));
  g.fill(0, 1, 3, 18, 13, a5(H5.caveFloor));
  g.set(0, 10, 14, a5(H5.caveFloor));
  // Waterfall down the north wall into a pool.
  g.fill(0, 3, 1, 4, 3, auto(K.waterfall));
  g.fill(0, 2, 4, 5, 5, auto(K.caveWater));
  g.points(2, HB.stalagmite, [[6, 8], [14, 6], [15, 11]]);
  g.set(2, 17, 3, HB.crystal);
  g.set(2, 12, 10, HB.bones);
  g.fill(5, 9, 3, 11, 5, 3);

  const events = [
    event(1, "Exit", 10, 14, [page({ trigger: 1, list: list(switchOff(S_IN_CAVE), transfer(1, 19, 1, 2, 2)) })]),
    // A counted goto loop (Label/Jump to Label) plus Get Location Info, Stop
    // SE, Select Item and the menu/save access flags: exercises the KRM3
    // command mappings with real MV parameter shapes.
    event(99, "Scout", 3, 13, [page({
      trigger: 0,
      list: list(
        cmd(134, 0), // Change Save Access: 0 disables
        cmd(135, 1), // Change Menu Access: nonzero enables
        cmd(122, 8, 0, 0, 0, 0), // v8 = 0
        cmd(118, "scout-loop"), // Label scout-loop
        cmd(122, 8, 8, 0, 1, 1), // v8 += 1
        cmd(285, 9, 0, 0, 3, 13), // v9 = terrain tag at (3,13), direct
        cmd(285, 10, 2, 0, 3, 13), // v10 = tile id on layer 1 at (3,13)
        cmd(104, 11, 1), // Select Item into v11, itypeId 1 (regular)
        cmd(251), // Stop SE
        ...ifThen(ifVar(8, 3, 3), [cmd(119, "scout-loop")]), // if v8 < 3 jump back
        cmd(135, 0), // Change Menu Access: 0 disables
        cmd(134, 1), // Change Save Access: nonzero enables
      ),
    })]),
    event(2, "Golem", 10, 4, [
      page({
        image: { characterName: "$Golem", characterIndex: 0 },
        list: list(
          mzText("Golem", "GRRR... who disturbs the deep?"),
          cmd(124, 0, 90),
          battle(
            1,
            [
              cmd(124, 1),
              switchOn(S_BOSS_DOWN),
              setVar(V_REWARD, 100),
              cmd(125, 0, 0, 100),
              mzText("", "The golem crumbles. You earn \\V[5]\\G."),
            ],
            [cmd(124, 1), addVar(V_ESCAPES, 1), mzText("", "You fled back into the dark.")],
            [cmd(124, 1), addVar(V_DEFEATS, 1), mzText("", "Beaten back... the golem still stands.")],
          ),
        ),
      }),
      page({ cond: whenSwitch(S_BOSS_DOWN), priority: 0, list: list() }),
    ]),
  ];
  return rmMap({ displayName: "Golem Cave", tilesetId: 2, grid: g, events, bgs: audio("hollow-cave", 60) });
}

function hollowData(files: Files): void {
  const put = (name: string, text: string) => writeData(files, HOLLOW, name, text);
  put(
    "System.json",
    j(
      system({
        flavor: "MZ",
        title: "Hollow",
        start: [1, 11, 9],
        switches: { [S_QUEST]: "QuestTaken", [S_GATE]: "GateOpen", [S_IN_CAVE]: "InCave", [S_BOSS_DOWN]: "BossDown", [S_PEACE]: "Peace" },
        variables: {
          [V_QUEST]: "Quest",
          [V_LUCK]: "Luck",
          [V_BONUS]: "Bonus",
          [V_REWARD]: "Reward",
          [V_ESCAPES]: "Escapes",
          [V_DEFEATS]: "Defeats",
          [V_TICKS]: "Ticks",
        },
        versionId: 41522093,
        partyMembers: [1],
      }),
    ),
  );
  put(
    "MapInfos.json",
    recordsJson([null, mapInfo(1, "Village", 1, 0), mapInfo(2, "House", 2, 1), mapInfo(3, "Cave", 3, 0)]),
  );
  const maps = [hollowVillage(), hollowHouse(), hollowCave()];
  maps.forEach((m, i) => put(mapFile(i + 1), mapJson(m)));
  put(
    "Tilesets.json",
    recordsJson([
      null,
      tileset(1, "Hollow Field", 0, HOLLOW_SHEETS, hollowFlags()),
      tileset(2, "Hollow Interior", 1, HOLLOW_SHEETS, hollowFlags()),
    ]),
  );
  const common: (RmCommonEvent | null)[] = [
    null,
    {
      id: 1,
      list: list(cmd(250, SE.chime), cmd(230, 30), mzText("", "A clear chime rings through the house.")),
      name: "Chime",
      switchId: 1,
      trigger: 0,
    },
    { id: 2, list: list(cmd(250, SE.drip), cmd(230, 90)), name: "Cave Drip", switchId: S_IN_CAVE, trigger: 2 },
  ];
  put("CommonEvents.json", recordsJson(common));
  put(
    "Items.json",
    recordsJson([
      null,
      item(I_POTION, "Potion", "Restores a little HP.", 20, 1, 176),
      item(I_PASS, "Cave Pass", "The elder's seal. Opens the north gate.", 0, 2, 195),
    ]),
  );
  put(
    "Weapons.json",
    recordsJson([null, weapon(1, "Oak Staff", "A sturdy walking staff.", 60, 8, 1), weapon(2, "Short Sword", "Light and sharp.", 100, 14, 2)]),
  );
  put("Armors.json", recordsJson([null, armor(1, "Cloth Vest", "Padded and warm.", 40, 5)]));
  put(
    "Actors.json",
    recordsJson([null, actor(1, "Wren", "People", 0, [1, 0, 0, 1, 0]), actor(2, "Moss", "People", 4, [2, 0, 0, 0, 0])]),
  );
  put("Classes.json", recordsJson(classes("Wanderer")));
  put("Skills.json", recordsJson(skills()));
  put("States.json", recordsJson(states()));
  put(
    "Enemies.json",
    recordsJson([
      null,
      {
        actions: [{ conditionParam1: 0, conditionParam2: 0, conditionType: 0, rating: 5, skillId: 1 }],
        battlerHue: 0,
        battlerName: "Golem",
        dropItems: [
          { dataId: 1, denominator: 1, kind: 0 },
          { dataId: 1, denominator: 1, kind: 0 },
          { dataId: 1, denominator: 1, kind: 0 },
        ],
        exp: 30,
        gold: 0,
        id: 1,
        name: "Golem",
        note: "",
        params: [120, 0, 14, 12, 8, 8, 6, 6],
        traits: [{ code: 22, dataId: 0, value: 0.95 }, { code: 31, dataId: 1, value: 0 }],
      },
    ]),
  );
  const troops: (RmTroop | null)[] = [
    null,
    {
      id: 1,
      members: [{ enemyId: 1, x: 240, y: 160, hidden: false }],
      name: "Golem",
      pages: [
        {
          conditions: {
            actorHp: 50, actorId: 1, actorValid: false, enemyHp: 50, enemyIndex: 0, enemyValid: false,
            switchId: 1, switchValid: false, turnA: 0, turnB: 0, turnEnding: false, turnValid: false,
          },
          list: list(),
          span: 0,
        },
      ],
    },
  ];
  put("Troops.json", recordsJson(troops));
  put("Animations.json", recordsJson([null]));
  files.set(`${HOLLOW}/game.rmmzproject`, "RPGMZ 1.8.0");
}

// =====================================================================================================
// Project B: stage-mv
// =====================================================================================================

const STAGE = "stage-mv";
const MV_SCALE = 3;

const S_SCENE_DONE = 1;
const S_LEAD_BOWED = 2;
const S_SMOKE = 3;
const S_STAGEHAND = 4;
const V_CLAPS = 1;
const V_ENCORE = 2;

const SB = { chair: 1, lip: 2, stairs: 3, rail: 4, spotlight: 5, smoke: 6, curtain: 7, plant: 8, drum: 9 } as const;
const SK = { stage: 16, carpet: 17, aisle: 18, top: 80, side: 88 } as const;
const S5 = { void: 0, pit: 1 } as const;

const STAGE_SHEETS = ["", "Stage_A2", "", "Stage_A4", "Stage_A5", "Stage_B", "", "", ""];

const MV_SE = {
  overture: audio("stage-overture", 80),
  crowd: audio("stage-crowd", 50),
  fanfare: audio("stage-fanfare"),
  applause: audio("stage-applause"),
  clap: audio("stage-clap"),
  step: audio("stage-step", 70),
  puff: audio("stage-puff", 70),
};

function stageB(): Map<number, TileDraw> {
  const velvet = rgb("#a01a2a");
  const wood = material(rgb("#7a5030"), "planks", 500);
  const brass = rgb("#d0a040");
  const t = new Map<number, TileDraw>();
  t.set(SB.chair, (c, x, y) => {
    c.rect(x + 2, y + 1, 12, 9, shade(velvet, 0.5));
    c.rect(x + 3, y + 2, 10, 7, velvet);
    c.rect(x + 2, y + 10, 12, 4, shade(velvet, 0.75));
    c.rect(x + 3, y + 14, 2, 2, rgb("#202020"));
    c.rect(x + 11, y + 14, 2, 2, rgb("#202020"));
  });
  t.set(SB.lip, (c, x, y) => {
    c.paint(x, y, TS, 6, (px, py) => texel(wood, px, py));
    c.rect(x, y + 6, TS, 10, shade(wood.base, 0.45));
    c.rect(x, y + 6, TS, 1, brass);
  });
  t.set(SB.stairs, (c, x, y) => {
    for (let s = 0; s < 4; s++) {
      c.rect(x + 1, y + s * 4, 14, 3, shade(wood.base, 1 - s * 0.12));
      c.rect(x + 1, y + s * 4 + 3, 14, 1, wood.edge);
    }
  });
  t.set(SB.rail, (c, x, y) => {
    c.rect(x + 7, y, 2, TS, brass);
    c.rect(x + 6, y + 2, 4, 2, shade(brass, 0.7));
    c.rect(x + 6, y + 12, 4, 2, shade(brass, 0.7));
  });
  t.set(SB.spotlight, (c, x, y) => {
    c.rect(x + 3, y + 3, 10, 10, rgb("#f0e8a0", 140));
    c.rect(x + 5, y + 5, 6, 6, rgb("#fff8d0", 200));
  });
  t.set(SB.smoke, (c, x, y) => {
    for (const [cx, cy, r] of [[5, 9, 4], [10, 7, 5], [8, 12, 3]] as const) {
      c.rect(x + cx - r, y + cy - r + 1, r * 2, r * 2 - 2, rgb("#c8c8d0", 170));
      c.rect(x + cx - r + 1, y + cy - r, r * 2 - 2, r * 2, rgb("#c8c8d0", 170));
    }
  });
  t.set(SB.curtain, (c, x, y) => {
    c.paint(x, y, TS, TS, (px) => ((px & 3) === 0 ? shade(velvet, 0.6) : (px & 3) === 2 ? shade(velvet, 1.2) : velvet));
    c.rect(x, y, TS, 2, brass);
  });
  t.set(SB.plant, (c, x, y) => {
    c.rect(x + 4, y + 10, 8, 6, rgb("#7a4a2a"));
    c.rect(x + 3, y + 2, 10, 9, rgb("#2a6a2a"));
    c.rect(x + 5, y + 1, 6, 2, rgb("#3a8a3a"));
  });
  t.set(SB.drum, (c, x, y) => {
    c.rect(x + 2, y + 4, 12, 10, shade(velvet, 0.6));
    c.rect(x + 3, y + 5, 10, 8, rgb("#e8e0d0"));
    c.rect(x + 2, y + 8, 12, 1, brass);
  });
  return t;
}

/** Five original 192 px MV animation cells, authored at one-third scale
 * beside the rest of the MV fixture art. */
function stageSparkleSheet(): Canvas {
  const c = new Canvas(5 * 64, 64);
  const colors = ["#fff4a0", "#80e8ff", "#ff90d8", "#b0ff90", "#d0b0ff"];
  for (let cell = 0; cell < 5; cell++) {
    const ox = cell * 64;
    const color = rgb(colors[cell]!);
    const glow = rgb(colors[cell]!, 110);
    const radius = 8 + cell * 2;
    c.rect(ox + 32 - radius, 31, radius * 2 + 1, 3, glow);
    c.rect(ox + 31, 32 - radius, 3, radius * 2 + 1, glow);
    for (let d = 0; d <= radius; d++) {
      const half = Math.max(1, Math.floor((radius - d) / 4));
      c.rect(ox + 32 - half, 32 - d, half * 2 + 1, 1, color);
      c.rect(ox + 32 - half, 32 + d, half * 2 + 1, 1, color);
      c.rect(ox + 32 - d, 32 - half, 1, half * 2 + 1, color);
      c.rect(ox + 32 + d, 32 - half, 1, half * 2 + 1, color);
    }
    c.rect(ox + 29, 29, 7, 7, rgb("#ffffff"));
    c.rect(ox + 18 + cell * 2, 18, 3, 3, color);
    c.rect(ox + 43, 42 - cell, 2, 2, color);
  }
  return c;
}

function stageClouds(): Canvas {
  const c = new Canvas(128, 64);
  c.paint(0, 0, c.w, c.h, (_x, y) => shade(rgb("#203858"), 0.75 + y / 160));
  for (const [x, y, w] of [[4, 13, 26], [45, 31, 34], [92, 8, 26]] as const) {
    c.rect(x, y + 3, w, 6, rgb("#7890a8", 210));
    c.rect(x + 4, y, w - 10, 9, rgb("#98a8b8", 210));
  }
  for (const [x, y] of [[12, 5], [57, 10], [108, 27], [30, 43]] as const) c.rect(x, y, 2, 2, rgb("#fff0b0"));
  return c;
}

function stageGlow(): Canvas {
  const c = new Canvas(128, 64);
  c.paint(0, 0, c.w, c.h, (x, y) => {
    const band = Math.abs(x - 64) + Math.floor(Math.abs(y - 32) / 2);
    return band < 18 ? rgb("#705070") : band < 34 ? rgb("#403858") : rgb("#181c38");
  });
  for (const x of [16, 64, 112]) {
    c.rect(x - 5, 13, 10, 14, rgb("#d09040"));
    c.rect(x - 3, 15, 6, 10, rgb("#ffe090"));
    c.rect(x - 1, 4, 2, 9, rgb("#b08040"));
  }
  return c;
}

function stageArt(files: Files): void {
  const img = (path: string, canvas: Canvas) => files.set(`${STAGE}/img/${path}`, canvas.scaled(MV_SCALE).png());
  // IconSet cells are always 32 px in MV as well as MZ; unlike map,
  // character, animation, picture, and parallax art they do not scale with
  // the project's 48 px tile size.
  const systemImg = (path: string, canvas: Canvas) => files.set(`${STAGE}/img/${path}`, canvas.png());
  const a2 = (kind: number): Material => {
    switch (kind) {
      case SK.stage: return material(rgb("#9a6a38"), "planks", 516);
      case SK.carpet: return material(rgb("#7a2a3a"), "weave", 517);
      case SK.aisle: return material(rgb("#b0303a"), "speckle", 518);
      default: return hueMaterial(kind + 7, "speckle");
    }
  };
  const a4 = (kind: number): Material => {
    switch (kind) {
      case SK.top: return material(rgb("#3a2a24"), "planks", 580);
      case SK.side: return material(rgb("#5a4a6a"), "planks", 588);
      default: return hueMaterial(kind + 7, Math.floor(kind / 8) % 2 === 0 ? "speckle" : "bricks");
    }
  };
  img("tilesets/Stage_A2.png", sheetA2(a2));
  img("tilesets/Stage_A4.png", sheetA4(a4));
  img(
    "tilesets/Stage_A5.png",
    sheetA5((i) =>
      i === S5.void
        ? plainTile(material(rgb("#101010"), "plain", 0))
        : i === S5.pit
          ? plainTile(material(rgb("#4a3a2a"), "planks", 601))
          : plainTile(hueMaterial(i + 600, "checker")),
    ),
  );
  img("tilesets/Stage_B.png", sheetB(stageB()));
  img(
    "characters/Cast.png",
    characterSheet([
      person(look("#2a1a10", "#e0a030", "#3a3a6a")), // 0 Ivy
      person(look("#f0d060", "#c03040", "#2a2a2a")), // 1 lead
      person(look("#8a2a8a", "#f080c0", "#f080c0")), // 2 dancer
      person(look("#3a3a3a", "#404850", "#303030")), // 3 stagehand
      person(look("#c86a2a", "#40a0a0", "#3a4a6a")), // 4 fan
      person(look("#f0d060", "#f0f0f0", "#d0b040")), // 5 lead in costume
      person(look("#1a1a1a", "#2a2a2a", "#2a2a2a")), // 6 usher
      person(look("#9a9a9a", "#6a8a4a", "#3a3a3a")), // 7
    ]),
  );
  img("characters/$Moth.png", singleSheet(moth(rgb("#d8d0b0"), rgb("#5a4a3a"))));
  img("system/Balloon.png", balloonSheet());
  systemImg("system/IconSet.png", fixtureIconSet());
  img("animations/Sparkle.png", stageSparkleSheet());
  img("parallaxes/StageClouds.png", stageClouds());
  img("parallaxes/!StageGlow.png", stageGlow());
  // Full-screen curtain (816 x 624 once scaled).
  const curtain = new Canvas(272, 208);
  const velvet = rgb("#a01a2a");
  curtain.paint(0, 0, 272, 208, (x) => {
    const fold = x % 16;
    return fold < 2 ? shade(velvet, 0.55) : fold < 6 ? shade(velvet, 0.8) : fold < 11 ? velvet : shade(velvet, 1.18);
  });
  curtain.rect(0, 0, 272, 18, shade(velvet, 0.6));
  curtain.rect(0, 18, 272, 2, rgb("#d0a040"));
  for (let x = 0; x < 272; x += 4) curtain.rect(x, 196, 2, 12, rgb("#d0a040"));
  curtain.rect(0, 194, 272, 2, rgb("#d0a040"));
  img("pictures/Curtain.png", curtain);
}

function stageMap(): RmMap {
  const g = new Grid(17, 13);
  g.fill(0, 0, 0, 16, 12, auto(SK.top));
  g.fill(0, 1, 1, 15, 1, auto(SK.side));
  g.fill(0, 1, 2, 15, 6, auto(SK.stage));
  g.fill(0, 1, 7, 15, 11, auto(SK.carpet));
  g.fill(0, 7, 7, 9, 11, auto(SK.aisle));
  g.fill(0, 11, 7, 15, 8, a5(S5.pit));
  // Transparent backdrop windows prove the authored parallax is really
  // below the tile plane. Clear both RM ground layers. The lower window at
  // x=7,y=5 exposes the right lantern away from the map-name banner.
  g.fill(0, 3, 0, 5, 1, 0);
  g.fill(1, 3, 0, 5, 1, 0);
  g.set(0, 7, 5, 0);
  g.set(1, 7, 5, 0);
  g.fill(5, 1, 2, 15, 5, 1);
  g.fill(4, 1, 2, 1, 5, 0b0101);
  g.points(2, SB.curtain, [[1, 1], [2, 1], [14, 1], [15, 1]]);
  // Stairs at x 3 and x 8 only: the fan's pen (x 11..15) stays sealed.
  for (let x = 1; x <= 15; x++) g.set(2, x, 6, x === 3 || x === 8 ? SB.stairs : SB.lip);
  for (const y of [9, 11]) {
    for (let x = 1; x <= 6; x++) g.set(2, x, y, SB.chair);
    for (let x = 10; x <= 15; x++) g.set(2, x, y, SB.chair);
  }
  // The fan's pen: stage lip above, chairs below, a rail on the west.
  g.points(2, SB.rail, [[10, 7], [10, 8]]);
  g.set(2, 1, 7, SB.plant);
  g.set(2, 15, 2, SB.drum);

  const leadRoute = route(
    [
      mv(R.speed, 4),
      mv(R.freq, 5),
      mv(R.right),
      mv(R.right),
      mv(R.turnDown),
      mv(R.wait, 20),
      mv(R.left),
      mv(R.left),
      mv(R.left),
      mv(R.left),
      mv(R.dirFixOn),
      mv(R.right),
      mv(R.dirFixOff),
      mv(R.throughOn),
      mv(R.down),
      mv(R.up),
      mv(R.throughOff),
      mv(R.lowerL),
      mv(R.upperR),
      mv(R.jump, 1, 0),
      mv(R.forward),
      mv(R.toward),
      mv(R.random),
      mv(R.turnRandom),
      mv(R.turnToward),
      mv(R.turn180),
      mv(R.turn90R),
      mv(R.turn90L),
      mv(R.opacity, 160),
      mv(R.opacity, 255),
      mv(R.se, MV_SE.step),
      mv(R.image, "Cast", 5),
      mv(R.switchOn, S_LEAD_BOWED),
    ],
    false,
    true,
    true,
  );
  const playerRoute = route([mv(R.up), mv(R.up), mv(R.turnUp), mv(R.wait, 10)], false, false, true);

  const director = page({
    trigger: 3,
    list: list(
      comment("Opening cutscene. Runs once; self switch A hands control back."),
      cmd(211, 0),
      cmd(221),
      cmd(241, MV_SE.overture),
      cmd(245, MV_SE.crowd),
      cmd(231, 1, "Curtain", 0, 0, 0, 0, 100, 100, 255, 0),
      cmd(222),
      cmd(230, 30),
      mvText("Ladies and gentlemen, welcome to the", "\\C[6]Lantern Stage\\C[0]!"),
      cmd(246, 2),
      cmd(232, 1, 0, 0, 0, 0, -624, 100, 100, 255, 0, 60, true),
      cmd(235, 1),
      cmd(211, 1),
      cmd(284, "!StageGlow", false, false, 0, 0),
      cmd(356, "StageLights dim 50"),
      cmd(223, [-34, -34, 0, 34], 30, true),
      cmd(249, MV_SE.fanfare),
      cmd(224, [255, 255, 224, 170], 20, true),
      cmd(213, -1, 1, true),
      setRoute(-1, playerRoute),
      cmd(212, 2, 1, true),
      setRoute(2, leadRoute),
      cmd(203, 2, 0, 8, 3, 2),
      cmd(213, 2, 4, false),
      mvText("\\C[2]Lead:\\C[0] Thank you, thank you!", "Now, a little rhythm from the wings..."),
      switchOn(S_SMOKE),
      cmd(225, 5, 5, 30, true),
      switchOn(S_STAGEHAND),
      loop(ifThen(ifVar(V_CLAPS, 1, 3), [cmd(113)]), cmd(230, 10)),
      cmd(250, MV_SE.applause),
      cmd(213, 4, 3, false),
      cmd(223, [0, 0, 0, 0], 30, true),
      mvText("The show begins! Have a word with the usher."),
      switchOn(S_SCENE_DONE),
      selfOn("A"),
    ),
  });

  const stagehandWalk = route(
    [mv(R.walkOn), mv(R.right), mv(R.right), mv(R.wait, 10), mv(R.left), mv(R.left), mv(R.turnDown)],
    false,
    true,
    true,
  );

  const events = [
    event(1, "Director", 0, 12, [director, page({ cond: whenSelf("A"), list: list() })]),
    event(2, "Lead", 8, 3, [
      page({ image: { characterName: "Cast", characterIndex: 1 }, list: list(mvText("Break a leg!")) }),
      page({
        cond: whenSwitch(S_LEAD_BOWED),
        image: { characterName: "Cast", characterIndex: 5 },
        list: list(mvText("Did you catch my bow?")),
      }),
    ]),
    event(3, "Dancer", 4, 4, [
      page({
        image: { characterName: "Cast", characterIndex: 2 },
        moveType: 3,
        speed: 4,
        route: route(
          [
            mv(R.stepOn),
            mv(R.right),
            mv(R.lowerR),
            mv(R.upperL),
            mv(R.left),
            mv(R.turn180),
            mv(R.wait, 20),
            mv(R.turnAway),
            mv(R.wait, 20),
          ],
          true,
          false,
          false,
        ),
        list: list(mvText("One, two, three, four!")),
      }),
    ]),
    event(4, "Fan", 13, 8, [
      page({
        image: { characterName: "Cast", characterIndex: 4 },
        moveType: 1,
        freq: 4,
        list: list(mvTextAt(1, 0, "Woo! Front row!")),
      }),
    ]),
    event(5, "Stagehand", 12, 3, [
      page({ image: { characterName: "Cast", characterIndex: 3 }, list: list(mvText("Places, everyone!")) }),
      page({
        cond: whenSwitch(S_STAGEHAND),
        image: { characterName: "Cast", characterIndex: 3 },
        trigger: 4,
        list: list(
          setRoute(0, stagehandWalk),
          cmd(250, MV_SE.clap),
          addVar(V_CLAPS, 1),
          ifThen(ifVar(V_CLAPS, 1, 3), [switchOff(S_STAGEHAND)]),
        ),
      }),
    ]),
    event(6, "Moth", 2, 8, [
      page({
        image: { characterName: "$Moth", characterIndex: 0 },
        moveType: 2,
        freq: 5,
        priority: 2,
        through: true,
        stepAnime: true,
        list: list(),
      }),
    ]),
    event(7, "Smoke", 6, 5, [
      page({ list: list() }),
      page({
        cond: whenSwitch(S_SMOKE),
        image: { tileId: SB.smoke },
        priority: 2,
        trigger: 4,
        list: list(cmd(250, MV_SE.puff), cmd(230, 45), cmd(214)),
      }),
    ]),
    event(8, "Spotlight", 8, 5, [
      page({
        image: { tileId: SB.spotlight },
        priority: 0,
        list: list(mvTextAt(2, 1, "A chalk mark: the lead's spot.")),
      }),
    ]),
    event(9, "Usher", 14, 10, [
      page({
        image: { characterName: "Cast", characterIndex: 6, direction: 4 },
        list: list(mvText("The show starts soon. Find your seat!")),
      }),
      page({
        cond: { ...whenSwitch(S_SCENE_DONE), variableId: V_CLAPS, variableValid: true, variableValue: 3 },
        image: { characterName: "Cast", characterIndex: 6, direction: 4 },
        list: list(
          ifThen(
            ifVar(V_CLAPS, 0, 3),
            [mvText("Three claps exactly! Bravo, \\N[1]."), setVar(V_ENCORE, 1), cmd(213, 0, 4, false)],
            [mvText("\\V[1] claps? The stagehand lost count.")],
          ),
        ),
      }),
    ]),
  ];
  return rmMap({
    displayName: "Lantern Stage",
    tilesetId: 1,
    grid: g,
    events,
    parallax: { name: "StageClouds", loopX: true, loopY: false, sx: 2, sy: 0, show: true },
  });
}

function stageData(files: Files): void {
  const put = (name: string, text: string) => writeData(files, STAGE, name, text);
  put(
    "System.json",
    j(
      system({
        flavor: "MV",
        title: "Lantern Stage",
        start: [1, 8, 10],
        switches: {
          [S_SCENE_DONE]: "SceneDone",
          [S_LEAD_BOWED]: "LeadBowed",
          [S_SMOKE]: "Smoke",
          [S_STAGEHAND]: "StagehandGo",
        },
        variables: { [V_CLAPS]: "Claps", [V_ENCORE]: "Encore" },
        versionId: 72005318,
        partyMembers: [1],
      }),
    ),
  );
  put("MapInfos.json", recordsJson([null, mapInfo(1, "Stage", 1, 0)]));
  put(mapFile(1), mapJson(stageMap()));
  put(
    "Tilesets.json",
    recordsJson([
      null,
      tileset(
        1,
        "Stage",
        1,
        STAGE_SHEETS,
        tilesetFlags({
          a5: { [S5.void]: F.block },
          b: {
            [SB.chair]: F.block,
            [SB.lip]: F.block,
            [SB.rail]: F.block,
            [SB.smoke]: F.star,
            [SB.curtain]: F.star,
            [SB.plant]: F.block,
            [SB.drum]: F.block,
          },
        }),
      ),
    ]),
  );
  put("CommonEvents.json", recordsJson([null]));
  put("Items.json", recordsJson([null, item(1, "Ticket", "Front row, center aisle.", 0, 2, 195)]));
  put("Weapons.json", recordsJson([null]));
  put("Armors.json", recordsJson([null]));
  put("Actors.json", recordsJson([null, actor(1, "Ivy", "Cast", 0, [0, 0, 0, 0, 0])]));
  put("Classes.json", recordsJson(classes("Performer")));
  put("Skills.json", recordsJson(skills()));
  put("States.json", recordsJson(states()));
  put("Enemies.json", recordsJson([null]));
  put("Troops.json", recordsJson([null]));
  put(
    "Animations.json",
    recordsJson([
      null,
      {
        animation1Hue: 0,
        animation1Name: "Sparkle",
        animation2Hue: 0,
        animation2Name: "",
        frames: [
          [[0, 0, 0, 50, 0, false, 255, 0]],
          [[1, -12, -12, 60, 25, false, 255, 0], [2, 16, 10, 35, -20, true, 192, 0]],
          [[3, 0, -24, 75, 90, true, 220, 0]],
          [[4, 12, -16, 40, 180, false, 180, 0]],
        ],
        id: 1,
        name: "Sparkle",
        position: 1,
        timings: [
          { flashColor: [255, 255, 224, 160], flashDuration: 5, flashScope: 1, frame: 0, se: MV_SE.puff },
          { flashColor: [160, 208, 255, 120], flashDuration: 3, flashScope: 2, frame: 2, se: SILENT },
        ],
      },
    ]),
  );
  files.set(`${STAGE}/Game.rpgproject`, "RPGMV 1.6.2");
}

// =====================================================================================================

/** Build every fixture file in memory. Keys are paths relative to the
 *  fixtures directory. */
export function buildFixtures(): Files {
  const files: Files = new Map();
  hollowData(files);
  hollowArt(files);
  stageData(files);
  stageArt(files);
  return files;
}

/** Write both projects under `outRoot`; returns the relative paths written,
 *  sorted. */
export function generateFixtures(outRoot: string): string[] {
  const files = buildFixtures();
  const paths = [...files.keys()].sort();
  for (const rel of paths) {
    const path = join(outRoot, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, files.get(rel)!);
  }
  return paths;
}

if (import.meta.main) {
  const out = process.argv[2] ?? new URL(".", import.meta.url).pathname;
  const written = generateFixtures(out);
  console.log(`rpgmaker fixtures: wrote ${written.length} files under ${out}`);
}
